= Syntax Versions

Since its inception in 2015, GSQL has evolved through three syntax versions: V1, V2, and V3.

* *V1 Syntax*: GSQL began with V1, which features a 1-hop-only data flow query language.
* *V2 Syntax*: The introduction of Pattern Match syntax in V2 marked a shift towards a more declarative approach. Users no longer need to consider data flow when writing queries, simplifying the query process.
* *V3 Syntax*: With the publication of ISO GQL in 2024, GSQL introduced the experimental V3 syntax. This version incorporates many Cypher-inspired elements, emphasizing ASCII art in its syntax.

== Differences Between Syntax Versions

* *V1 vs. V2*: For detailed differences between V1 and V2, please refer to xref:gsql-ref:querying:syntax-versions.adoc[Differences Between V1 and V2]
* *V2 vs. V3*: The variations between V2 and V3 are primarily syntactic, with V3 placing a stronger emphasis on ASCII art.

=== How to Specify a Syntax Version
Users can specify the syntax version for a query in its signature. This is done by including the "Syntax Version" after the parameter parentheses and before the query body begins.

==== Example

* q1 uses syntax V1

[source,gsql]
----
CREATE OR REPLACE DISTRIBUTED QUERY q1(/* parameters */) SYNTAX V1 {
// Query body for V1 syntax
}
----

* q2 uses syntax V2
[source,gsql]
----
CREATE OR REPLACE DISTRIBUTED QUERY q2(/* parameters */) SYNTAX V2 {
// Query body for V2 syntax
}
----


* q3 uses syntax V3

[source,gsql]
----
CREATE OR REPLACE DISTRIBUTED QUERY q3(/* parameters */) SYNTAX V3 {
// Query body for V3 syntax
}
----
By clearly specifying the syntax version, users can leverage the unique features and improvements of each version to optimize their queries.




