= Control Flow Statements
:description: Reference for control flow statements in the GSQL query language.
:stem: latexmath

The GSQL Query Language includes a comprehensive set of control flow statements to empower sophisticated graph traversal and data computation: `IF/ELSE`, `CASE`, `WHILE`, and `FOREACH`.

[#_differences_in_block_syntax]
== Differences in Block Syntax

Note that any of these statements can be used as a query-body statement or as a DML-sub level statement.

If the control flow statement is at the query-body level, then its block(s) of statements are query-body statements ( _queryBodyStmts_ ).
In a _queryBodyStmts_ block, each individual statement ends with a semicolon, so there is always a semicolon at the end.

If the control flow statement is at the DML-sub level, then its block(s) of statements are DML-sub statements ( _dmlSubStmtList_ ).
In a _dmlSubStmtList_ block, a comma separates statements, but there is no punctuation at the end.

For more detailed general examples of the difference between query-body statements and DML-sub statements, see xref:query-operations.adoc#_statement_types[statement types].

== `IF` Statement

The `IF` statement provides conditional branching: execute a block of statements ( `queryBodyStmts` or `dmlSubStmtList` ) only if a given _condition_ is true.
The `IF` statement allows for zero or more `ELSE-IF` clauses, followed by an optional `ELSE` clause.
The `IF` statement can be used either at the query-body level or at the DML-sub-statement level. (See the xref:querying:control-flow-statements.adoc#_differences_in_block_syntax[note about differences in block syntax].)


=== Syntax
.`IF` syntax
[source,ebnf]
----
queryBodyIfStmt := IF condition THEN queryBodyStmts
                 [ELSE IF condition THEN queryBodyStmts ]*
                 [ELSE queryBodyStmts ] END
dmlSubIfStmt :=    IF condition THEN dmlSubStmtList
                 [ELSE IF condition THEN dmlSubStmtList ]*
                 [ELSE dmlSubStmtList ] END
----

If an `IF` condition is not true, then the flow proceeds to the next `ELSE IF` condition.
When a true condition is encountered, its corresponding block of statements is executed, and then the `IF` statement terminates (skipping any remaining `ELSE-IF` or `ELSE` clauses).
If an `ELSE` clause is present, its block of statements are executed if none of the preceding conditions are true.
Overall, the functionality can be summarized as "execute the first block of statements whose conditional test is true."

.IF semantics
[source,gsql]
----
// if then
IF x == 5 THEN y = 10; END;      # y is assigned to 10 only if x is 5.

// if then else
IF x == 5 THEN y = 10;       # y is 10 only if x is 5.
ELSE y = 20; END;            # y is 20 only if x is NOT 5.

// if with ELSE IF
IF x == 5 THEN y = 10;       # y is 10 only if x is 5.
ELSE IF x == 7 THEN y = 5;   # y is 5  only if x is 7.
ELSE y = 20; END;            # y is 20 only if x is NOT 5 and NOT 7.
----

=== Examples

[tabs]
====
Query::
+
--
This query counts the number of friends a person has, and optionally include coworkers in that count

.Simple IF-ELSE at query-body level
[source,gsql]
----
include::appendix:example$friend_net/controlflow_ifelse_querybody.gsql[]
----
--
Results::
+
--
[source,gsql]
----
GSQL > RUN QUERY count_friends_of2("person2", false)
include::appendix:example$friend_net/controlflow_ifelse_querybody_results.json[]
----
--
====

[tabs]
====
Query::
+
--
This query uses a more advanced activity calculation, taking into account number of posts and number of likes that a user made.

[source,gsql]
----
include::appendix:example$social_net/controlflow_nested_ifelse.gsql[]
----
--

Results::
+
--
[source,gsql]
----
GSQL > RUN QUERY calculate_in_depth_activity("person1")
include::appendix:example$social_net/controlflow_nested_ifelse_results.json[]
----
--
====



== `CASE` Statement

The `CASE` statement provides conditional branching: execute a block of statements only if a given condition is true.
`CASE` statements can be used as query-body statements or DML-sub-statements. (See <<_differences_in_block_syntax,note about differences in block syntax>>.)

=== Syntax
.`CASE` syntax
[source,ebnf]
----
queryBodyCaseStmt := CASE  (WHEN condition THEN queryBodyStmts)+ [ELSE queryBodyStmts] END
               | CASE expr (WHEN constant  THEN queryBodyStmts)+ [ELSE queryBodyStmts] END
dmlSubCaseStmt := CASE     (WHEN condition THEN dmlSubStmtList)+ [ELSE dmlSubStmtList] END
               | CASE expr (WHEN constant  THEN dmlSubStmtList)+ [ELSE dmlSubStmtList] END
----


One `CASE` statement contains one or more `WHEN-THEN` clauses, each `WHEN` presenting one expression.
The `CASE` statement may also have one `ELSE` clause whose statements are executed if none of the preceding conditions are true.

There are two syntax of the `CASE` statement: one equivalent to an if-else statement, and the other is structured like a switch statement.
The if-else version evaluates the boolean _condition_ within each `WHEN` clause and executes the first block of statements whose _condition_ is true.
The optional concluding `ELSE` clause is executed only if all `WHEN` clause conditions are false.

The switch version evaluates the expression following the keyword `WHEN` and compares its value to the expression immediately following the keyword `CASE`.
These expressions do not need to be boolean; the `CASE` statement compares pairs of expressions to see if their values are equal.
The first `WHEN-THEN` clause to have an expression value equal to the `CASE` expression value is executed; the remaining clauses are skipped. The optional `ELSE` clause is executed only if no `WHEN` clause expression has a value matching the `CASE` value.

.CASE Semantics
[source,gsql]
----
STRING drink = "Juice";

// CASE statement: if-else version
CASE
  WHEN drink == "Juice" THEN @@calories += 50
  WHEN drink == "Soda"  THEN @@calories += 120
  ...
  ELSE @@calories = 0       // Optional else-clause
END
// Since drink = "Juice", 50 will be added to calories

// CASE statement: switch version
CASE drink
  WHEN "Juice" THEN @@calories += 50
  WHEN "Soda"  THEN @@calories += 120
  ...
  ELSE  @@calories = 0    // Optional else-clause
END
// Since drink = "Juice", 50 will be added to calories
----


=== Examples


[tabs]
====
Query::
+
--
This query tallies male and female friends of the starting vertex.

[source,gsql]
----
include::appendix:example$social_net/controlflow_case.gsql[]
----
--

Results::
+
--
.Example 2 Results for Query countGenderOfFriends
[source,gsql]
----
GSQL > RUN QUERY countGenderOfFriends("person4")
include::appendix:example$social_net/controlflow_case_results.json[]
----
--
====


[tabs]
====
Query::
+
--
This query gives each user post a rating based on the subject and how many likes it has.

[source,gsql]
----
include::appendix:example$social_net/controlflow_nested_case.gsql[]
----
--

Results::
+
--
.Example 4 Results for Query ratePosts
[source,gsql]
----
GSQL > RUN QUERY ratePosts()
include::appendix:example$social_net/controlflow_nested_case_results.json[]
----
--
====


== `WHILE` Statement

The WHILE statement provides unbounded iteration over a block of statements. WHILE statements can be used as query-body statements or DML-sub-statements. (See the xref:querying:control-flow-statements.adoc#_differences_in_block_syntax[note about differences in block syntax].)

=== Syntax
.WHILE syntax
[source,ebnf]
----
queryBodyWhileStmt := WHILE condition [LIMIT simpleSize] DO queryBodyStmts END
dmlSubWhileStmt :=    WHILE condition [LIMIT simpleSize] DO dmlSubStmtList END
simpleSize := integer | varName | paramName
----

The `WHILE` statement iterates over its body ( _queryBodyStmts_ or _dmlSubStmtList_ ) until the _condition_ evaluates to false or until the iteration limit is met.  A _condition_ is any expression that evaluates to a boolean.
The condition is evaluated before each iteration. `CONTINUE` statements can be used to change the control flow within the while block. `BREAK` statements can be used to exit the while loop.

A `WHILE` statement may have an optional `LIMIT` clause.
`LIMIT` clauses has a constant positive integer value or integer variable to constrain the maximum number of loop iterations.
The example below demonstrates how the `LIMIT` behaves.

[CAUTION]
====
If a limit value is not specified, it is possible for a WHILE loop to iterate infinitely. It is the responsibility of the query author to design the condition logic so that it is guaranteed to eventually be true (or to set a limit).
====

The following three `WHILE` statements behave the same.
Each terminates when `v.size == 0` or after 5 iterations of the loop.

.WHILE LIMIT semantics
[source,gsql]
----
WHILE v.size() !=0 LIMIT 5 DO
    // Statements
END;

INT iter = 0;
WHILE (v.size() !=0) AND (iter < 5) DO
    // Statements
    iter = iter + 1;		
END;

INT iter = 0;
WHILE v.size() !=0 DO
    IF iter == 5 THEN  BREAK;  END;
    // Statements
	iter = iter + 1;	
END;
----

=== Examples

Below are a number of examples that demonstrate the use of `WHILE` statements.

[tabs]
====
Query::
+
--
The following query finds all vertices which are reachable from a starting seed vertex (i.e., breadth-first search)

.Example 1. Simple WHILE loop
[source,gsql]
----
include::appendix:example$work_net/controlflow_while.gsql[]
----
--

Results::
+
--

[source,gsql]
----
RUN QUERY reachable("person1")
include::appendix:example$work_net/controlflow_while_results.json[]
----
--
====

[tabs]
====
Query::
+
--
This query finds all vertices reachable within two hops from a starting seed vertex (i.e., breadth-first search)

[source,gsql]
----
include::appendix:example$work_net/controlflow_while_2.gsql[]
----
--

Results::
+
--

[source,gsql]
----
include::appendix:example$work_net/controlflow_while_2_run.gsql[]
include::appendix:example$work_net/controlflow_while_2_results.json[]
----
--
====


[#_foreach_statement]
== `FOREACH` Statement

The `FOREACH` statement provides bounded iteration over a block of statements. `FOREACH` statements can be used as query-body statements or DML-sub-statements.
See the xref:querying:control-flow-statements.adoc#_differences_in_block_syntax[note about differences in block syntax].

=== Syntax
.`FOREACH` syntax
[source,ebnf]
----
queryBodyForEachStmt := FOREACH forEachControl DO queryBodyStmts END
dmlSubForEachStmt :=    FOREACH forEachControl DO dmlSubStmtList END

forEachControl := ( iterationVar | "(" keyVar ("," valueVar)+ ")") (IN | ":") setBagExpr
                | iterationVar IN RANGE "[" expr "," expr"]" ["." STEP(" expr ")"]
iterationVar := name
keyVar := name
valueVar := name
----

The formal syntax for `forEachControl` appears can be broken down into the following cases:

* `name IN setBagExpr`
* `(key, value) pair IN setBagExpr` // because it's a Map
* `name IN RANGE [ expr, expr ]`
* `name IN RANGE [ expr, expr ].STEP ( expr )`

Note that `setBagExpr` includes container accumulators and explicit sets.

=== Limitations
The `FOREACH` statement has the following restrictions:

* In a DML-sub level `FOREACH`, it is never permissible to update the loop variable (the variable declared before `IN`, e.g., `var` in "`FOREACH var IN setBagExpr`").
* In a query-body level `FOREACH`, in most cases it is not permissible to update the loop variable.
The following exceptions apply:
 ** If the iteration is over a `ListAccum`, its values can be updated.
 ** If the iteration is over a `MapAccum`, its values can be updated, but its keys cannot.
* If the iteration is over a set of vertices, it is not permissible to access (read or write) their vertex-attached accumulators.
* A query-body-level `FOREACH` cannot iterate over a set or bag of constants.
For example, `FOREACH` i in (1,2,3) is not supported.
However, DML-sub `FOREACH` does support this.

=== `FOREACH ... IN RANGE`

The `FOREACH` statement has an optional `RANGE` clause `RANGE[expr, expr]`, which can be used to define the iteration collection.
Optionally, the range may specify a step size:
`RANGE[expr, expr].STEP(expr)`

Each `expr` must evaluate to an integer.
Any of the integers may be negative, but the step `expr` may not be 0.

The clause `RANGE[a,b].STEP(c)`  produces the sequence of integers from `a` to `b`, inclusive, with step size `c`.
That is,
stem:[(a, a+c, a+2*c, a+3*c, ... a+k*c)], where k = the largest integer such that stem:[|k*c| ≤ |b-a|].

If the `.STEP` method is not given, then the step size c = 1.

[tabs]
====
Query::
+
--
.Nested `FOREACH IN RANGE` with MapAccum
[source,gsql]
----
include::appendix:example$social_net/controlflow_foreach_range.gsql[]
----
--

Results::
+
--
.Results for Query foreachRangeEx
[source,gsql]
----
GSQL > RUN QUERY foreachRangeEx()
include::appendix:example$social_net/controlflow_foreach_range_results.json[]
----
--
====

[tabs]
====
Query::
+
--
The following `FOREACH` statement uses a specified step value for iterating through the range.

[source,gsql]
----
include::appendix:example$minimal_net/controlflow_foreach_step.gsql[]
----
The step value can be positive for an ascending range or negative for a descending range.
If the step has the wrong polarity, then the loop has zero iterations; that is, the exit condition is already satisfied.
--

Results::
+
--

[source,gsql]
----
GSQL > RUN QUERY foreachRangeStep(100,0,-9)
include::appendix:example$minimal_net/controlflow_foreach_range_results.json[]
----
--
====


=== Query-body-level FOREACH Examples

[tabs]
====
Query::
+
--
This query counts the number of companies whose country matches the provided string.

[source,gsql]
----
include::appendix:example$work_net/controlflow_querybody_foreach.gsql[]
----
--

Results::
+
--
[source,gsql]
----
include::appendix:example$work_net/controlflow_querybody_foreach_run.gsql[]
include::appendix:example$work_net/controlflow_querybody_foreach_results.json[]
----
--
====

[tabs]
====
Query::
+
--
This query counts the number of employees from a given country and list their IDs.

[source,gsql]
----
include::appendix:example$work_net/controlflow_querybody_foreach_2.gsql[]
----
--

Results::
+
--

[source,gsql]
----
include::appendix:example$work_net/controlflow_querybody_foreach_2_run.gsql[]
include::appendix:example$work_net/controlflow_querybody_foreach_2_results.json[]
----
--
====


=== DML-sub FOREACH Examples

[tabs]
====
Query::
+
--
This query shows post topics liked by users and show total likes per topic.

[source,gsql]
----
include::appendix:example$social_net/controlflow_dmlsub_foreach.gsql[]
----
--

Results::
+
--

[source,gsql]
----
GSQL > RUN QUERY topicLikes()
include::appendix:example$social_net/controlflow_dmlsub_foreach_results.json[]
----
--
====

[tabs]
====
Query::
+
--
This query shows a summary of the number of friends all persons have by gender.

[source,gsql]
----
include::appendix:example$social_net/controlflow_dmlsub_foreach_2.gsql[]
----
--

Results::
+
--

[source,gsql]
----
GSQL > RUN QUERY friendGender()
include::appendix:example$social_net/controlflow_dmlsub_foreach_2_results.json[]
----
--
====


== `CONTINUE` and `BREAK` Statements

The `CONTINUE` and `BREAK` statements can only be used within a block of a `WHILE` or `FOREACH` statement.
The `CONTINUE` statement branches control flow to the end of the loop, skipping any remaining statements in the current iteration, and proceeding to the next iteration.
That is, everything in the loop block after the `CONTINUE` statement will be skipped, and then the loop will continue as normal.

The `BREAK` statement branches control flow out of the loop, i.e., it will exit the loop and stop iteration.

=== Examples
Below are a number of examples that demonstrate the use of `BREAK` and `CONTINUE`.

.Continue and Break Semantics
[source,gsql]
----
// While loop with continue statement
    INT i = 0;
    INT nCount = 0;
    WHILE i < 10 DO
        i = i + 1;
        IF (i % 2 == 0) { CONTINUE; }
        nCount = nCount + 1;
    END;
    // i is 10, nCount is 5 (skips the increment for every even i).

    // While loop with a break statement
    i = 0;
    WHILE i < 10 DO
        IF (i == 5) { BREAK; }  # When i is 5 the loop is exited
        i = i + 1;
    END;
// i is now 5
----

[tabs]
====
Query::
+
--
This query finds posts of a given person, and post of friends of that person, friends of friends, etc. until a post about cats is found.
The number of friend-hops to reach is the 'degree' of cats.

[source,gsql]
----
include::appendix:example$social_net/controlflow_break.gsql[]
----
--

Results::
+
--
[source,gsql]
----
GSQL > RUN QUERY findDegreeOfCats("person2")
include::appendix:example$social_net/controlflow_break_results.json[]
----
--
====

[tabs]
====
Query::
+
--
This query finds all 3-hop friends of a starting vertex.
Count coworkers as friends if there are not enough friends

[source,gsql]
----
include::appendix:example$friend_net/controlflow_continue.gsql[]
----
--

Results::
+
--
.findEnoughFriends.json Example 2 Results
[source,gsql]
----
GSQL > RUN QUERY findEnoughFriends("person1")
include::appendix:example$friend_net/controlflow_continue_results.json[]
----
--
====
