= GSQL Query Language
:page-aliases: introduction-query.adoc
:description: Overview of the GSQL Query Language.

The GSQL ® Query Language is a language for the exploration and analysis of large scale graphs.
The high-level language makes it easy to perform powerful graph traversal queries in the TigerGraph system.
By combining features familiar to database users and programmers with highly expressive new capabilities, the GSQL query language offers both easy authoring and powerful execution.

== What is a GSQL query?

A GSQL query is a sequence of data retrieval-and-computation statements executed as a single operation.
Users can write queries to explore a data graph however they like, to read and make computations on the graph data along the way, to update the graph, and to deliver resulting data.
A query is analogous to a user-defined procedure or function: it can have one or more input parameters, and it can produce output in two ways: by returning a value or by printing.

Though GSQL is SQL-like, an important distinction between SQL and GSQL queries is that a GSQL query is a sequence of statements defined as a single operation, while a SQL query tends to be a single statement that executes directly against a database.


== Query syntax versions

The current default syntax version for GSQL queries is Syntax V2.
Most documentation in this section describes the language in Syntax V2.
To see the different between the legacy version and V2, see xref:querying:syntax-versions.adoc[].

== Query operations

A typical workflow for working with GSQL queries is to xref:query-operations.adoc#_create_query[create the query], xref:query-operations.adoc#_install_query[install the query], and then xref:query-operations.adoc#_run_query[run the query].

GSQL also supports xref:query-operations.adoc#interpret-a-created-query[interpreting a query], which allows users to skip query installation and execute the query directly.

== Syntax

The following pages describes the syntax of the GSQL Query Language:

* xref:data-types.adoc[]
* xref:query-operations.adoc[]
* xref:data-types.adoc[]
* xref:accumulators.adoc[]
* xref:operators-and-expressions.adoc[]
* xref:func/index.adoc[]
* xref:declaration-and-assignment-statements.adoc[]
* xref:select-statement/index.adoc[]
* xref:select-statement/sql-like-select-statement.adoc[]
* xref:control-flow-statements.adoc[]
* xref:data-modification-statements.adoc[]
* xref:output-statements-and-file-objects.adoc[]
* xref:exception-statements.adoc[]
* xref:comments.adoc[]

== Example graphs

It includes example queries that demonstrate the language, each of which works on one of the following six graphs: `Work_Net`, `Social_Net`, `Friend_Net`, `Computer_Net`, `Minimal_Net`, and `Investment_Net`.

The data sets are small so that you can understand the result of each query example.
The following file `gsql_ref_examples_2.0.tar.gz`) contains all graph schemas, data files, and queries.

link:{attachmentsdir}/gsql_ref_examples_2.0.tar.gz[Download graph files and loading script].

