= Write Query Output to Cloud

[#_write_query_data_to_s3]
== Write Query Output to S3 File Object
To output query results to S3, connection credentials need to be set first.
S3 connection credentials can be set at cluster level using gadmin config. Another way to set S3 connection credentials is using GSQL Session Parameters which supports idea of multi user multi session.

To use an S3 path, ensure that the necessary permissions and configurations are properly set up to allow read/write access to the specified S3 bucket.

To see how to define a S3 File Object, refer to xref:data-types.adoc#_define_s3_file_object[Define s3 file object].
[#_step_1]
==== Configure S3 connection credentials using gadmin config
[source,bash]
----
gadmin config set GPE.QueryOutputS3AWSAccessKeyID YOUR_AWS_ACCESS_KEY_ID
gadmin config set GPE.QueryOutputS3AWSSecretAccessKey YOUR_AWS_SECRET_ACCESS_KEY
gadmin config apply -y
gadmin restart gpe -y
----
==== Configure S3 connection credentials using GSQL session parameters
[source,bash]
----
set s3_aws_access_key_id ="YOUR_AWS_ACCESS_KEY_ID"
set s3_aws_secret_access_key ="YOUR_AWS_SECRET_ACCESS_KEY"
----
The connection credentials are configured only for current user and current session. After setting these session parameters, all existing and future queries in this session will use these connection credentials to write query output to S3 File objects.

==== Output
Since S3 is a shared storage system, multiple nodes in a cluster can upload to the same S3 bucket. 

To handle potential conflicts and ensure unique output files, the S3 path can include a prefix based on the instance name, such as `\GPE_{PartitionId}_{ReplicaId}`. For distributed queries, additional suffixes will be used to differentiate between the manager and worker roles on the same GPE. Specifically, prefixes like `_coordinator` and `_worker` will be added, where `_coordinator` refers to the worker manager and `_worker` refers to the worker node.

The prefixes for files written by worker manager node and worker node are  `\GPE_{PartitionId}_{ReplicaId}_coordinator` and `\GPE_{PartitionId}_{ReplicaId}_worker` respectively.

==== Error code
For S3 bucket connection errors, refer to error code `GSQL-5301`.
