= GSQL Endpoints
:pp: {plus}{plus}
:description: A set of GSQL REST API endpoints about vertex in TigerGraph server.
:toc:

This page describes the REST API endpoints accessible on a TigerGraph server.

[NOTE]
====
*Note for users of TigerGraph Cloud*

For all TigerGraph Cloud solutions created on or after June 20, 2022, ports 14240 and 9000 are no longer exposed.
This also applies to previously created cloud solutions that are resized on or after June 20, 2022. Use port 443 instead for API endpoint connectivity on cloud solutions:

** Use API endpoint `443/restpp/<endpoint>` for RESTPP endpoints that were on port 9000

** Use API endpoint `443/<endpoint>` for endpoints that were on port 14240

For all TigerGraph Server solutions not on TigerGraph Cloud, or for TigerGraph Cloud solutions created before June 20, 2022, ports 9000 and 14240 remain correct.
====

== Schema

=== show local vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.


==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices?graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''
=== show all global vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"uid"},"Name":"user"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"wid"},"Name":"website"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"pid"},"Name":"product"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user2"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"DATETIME"},"AttributeName":"dob"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user3"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----
--
====

==== Parameters:

None

'''
=== show a local vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/house?graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"IsLocal":true,"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"house"}}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''        
=== show a global vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/person"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"}}
----
--
====

==== Parameters:

NONE

'''     

=== create vertex usgin gsql command 

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/vertices?gsql=true" -d '{"gsql":["CREATE VERTEX UserA (PRIMARY_ID user_id UINT, name STRING)", "CREATE VERTEX UserB (PRIMARY_ID user_id UINT, name STRING)"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create vertices: [UserA, UserB]"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== create vertex (add global vertex to local graph)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false&graph=empty_graph" -d '{"addVertices":["user","website"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully add vertices: [user, website] on graph empty_graph"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create vertex (create vertex in global level)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false" -d '{"createVertices":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User5"},
{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User4"}
]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create vertices: [User5, User4]"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dorp all the vertices
|===

'''  

=== drop local vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3&graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dropping all the vertices

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  

=== drop a local vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to be deleted
|===


'''  
=== drop a global vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2] deleted successfully."}
----
--
====
==== Parameters:

None

'''  
=== update vertex attribute (local graph)

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user?graph=recommend" -d '{"dropAttributes":["area"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr1"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update vertex: user"}
----
--
====
==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to update
|===

'''  
=== update a global vertex attribute

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update vertex: user"}
----
--
====
==== Parameters:

None

'''  
===  show all indexes
`GET /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"person":[{"index":"canSpeak_index","attribute":"canSpeak"}]}]}
----
--
====
==== Parameters:

None

'''  
=== show all indexes on a graph
`GET /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=recommend" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"house":[{"index":"height_type_name","attribute":"height"},{"index":"Index_Type_Name","attribute":"area"}]}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the indexes in which graph to show
|===

'''  
=== show an index
`GET /gsql/v1/schema/indexes/{indexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes/Index_Type_Name?graph=recommend" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"index":"Index_Type_Name","attribute":"area"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the indexes in which graph to show
|===

'''  
=== create indexes
`POST /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=recommend" -d '{"vertex":"house","addIndexAttributes":[{"indexName":"areaIndex","attributeName":"area"},{"indexName":"heightIndex","attributeName":"height"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully add index areaIndex on attribute area\nSuccessfully add index heightIndex on attribute height\n"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the indexes in which graph to create
|===

'''  
=== drop an index
`DELETE /gsql/v1/schema/indexes/{indexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?vertex=name1&graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully drop index"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertex`
| yes
| the vertex on which to drop index

| `graph`
| no
| the indexes in which graph to drop
|===

'''  
=== drop indexes
`DELETE /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=g&vertex=name1 &indexName=index1,index2"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully drop index"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertex`
| yes
| the vertex on which to drop index

| `indexName`
| yes
| the indexes to drop (seperate by ,)

| `graph`
| no
| the indexes in which graph to drop
|===

'''  
=== get all global edges 

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"},{"IsDirected":true,"ToVertexTypeName":"website","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"has_account"},{"IsDirected":false,"ToVertexTypeName":"website","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"item_id"}],"FromVertexTypeName":"product","Name":"sell_on"},{"IsDirected":true,"ToVertexTypeName":"product","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"viewed"},{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----
--
====
==== Parameters:

None

'''
=== get all edges in graph

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===

'''
=== get a global specific edge type info

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/purchase"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"}}
----
--
====
==== Parameters:

None

'''        
=== get a specific edge type info (under graph)

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/roles?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===


'''     

=== create edges using gsql command statement

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/edges?gsql=true" -d '{"gsql":["CREATE UNDIRECTED EDGE edge1 (from user3, to product, attr1 float)", "CREATE UNDIRECTED EDGE edge2 (from user2, to product, attr2 float)"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== add global edges to graph using json format

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false&graph=empty_graph" -d '{"addEdges":["has_account"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":true,"message":"Failed to create edges [has_account]. Semantic Check Fails: The schema change job tries to add edge has_account to graph empty_graph, but the FROM vertex type user does not exist on the graph.\n"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create global edges using json format 

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false" -d ' {"createEdges":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr1"}],"FromVertexTypeName":"user3","Name":"edge1"},{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr2"}],"FromVertexTypeName":"user2","Name":"edge2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global edges

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=test1"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped edges: [test1]."}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|===

'''  

=== drop edges from graph

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=e1&graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Edges [e1] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  
=== drop an local edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Edges [e1] deleted successfully."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be deleted
|===


'''  
=== drop a global edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/test1"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped edges: [test1]."}
----
--
====

==== Parameters:

None

'''  
=== update attribute in edge in global level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/purchase" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update edge: purchase"}
----
--
====
==== Parameters:

None

'''  
=== update attribute in edge in local level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update edge: e1"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be update
|===


'''  
=== show all graphs info only containing names of vertices and edges

`GET /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs"
----
--
Response::
+
--
[source.wrap,console]
----
{"graphs":[{"graphName":"recommend","vertices":["user","website","product","user2","user3"],"edges":["purchase","has_account","sell_on","viewed"]},{"graphName":"person_movie","vertices":["person","movie"],"edges":["roles","roles2"]}],"error":false,"message":""}
----
--
====
==== Parameters:

None

'''  
=== show one graph detailed info with given graph name


`GET /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?graphName=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----

{"error":false,"message":"","results":{"GraphName":"person_movie","VertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}],"EdgeTypes":[{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}}
 
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph whose schema to show
|===

=== create one graph using gsql command


`POST /gsql/v1/schema/graphs?gsql=true`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?gsql=true" -d '{"gsql": "create graph g(*)"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created graph: [g]."} 
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| true, means using gsql command
|===

'''  

=== create one graph using JSON format 

`POST /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?graphName=gtest&gsql=false
" -d '{"VertexTypes":["user","product"], "EdgeTypes":["purchase"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created graph: [gtest]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| false, means using JSON

| `graphName`
| yes
| the graph name
|===

'''  

=== drop one graph

`DELETE /gsql/v1/schema/graphs/{graphName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/graphs/person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped graph: person_movie."}
----
--
====
==== Parameters:

None

'''  

=== drop graphs with given names

`DELETE /gsql/v1/schema/graphs/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/graphs?graphNames=person_movie,recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped graphs: [person_movie, recommend]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graphNames`
| yes
| the graph names(separate by `,`), all means drop all the graphs
|===

'''  
=== drop local/global scheme change job

`DELETE /gsql/v1/schema/jobs/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/jobs?jobName=test1,test2&graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped schema change jobs: [test1, test2]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `jobName`
| yes
| the schema jobs to drop (separate by `,`) 

| `graph`
| no
| the graph whose jobs to drop.
|===

'''  
=== create local/global scheme change job using gsql command

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/jobs/test3?gsql=true&type=global" -d ' {"gsql" : "create global schema_change job test3 {add vertex website to graph person_movie;}"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created global schema change job: [test3]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| `true`, means using gsql command

| `type`
| yes
| when `global` means create global schema change, `local` means create local schema change.
|===

'''  
=== create global scheme change job using json

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test4?gsql=false&type=global" -d '{"graphs": [{"graphName":"empty_graph","addVertexTypes":["user","website"],"dropVertexTypes":[], "dropEdgeTypes":[],"addEdgeTypes":[]}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created global schema change job: [test4]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| false
| `true`, means post body using json 

| `type`
| yes
| `global`, means create global schema change
|===

'''  
=== create local scheme change job using json

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test5?type=local&graph=recommend" -d 
'{
    "dropVertexTypes": [
        "desk"
    ],
    "alterVertexTypes": [
        {
            "name": "house",
            "dropAttributes": [
                "height"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "dropIndexAttributes": [
                {
                    "indexName": "Index_Type_Name",
                    "attributeName": "area"
                }
            ],
            "addIndexAttributes": [
                {
                    "indexName": "ppIndex",
                    "attributeName": "pp"
                }
            ]
        }
    ],
    "addVertexTypes": [
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User5"
        },
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User4"
        }
    ],
    "addEdgeTypes": [
        {
            "IsDirected": true,
            "ToVertexTypeName": "User4",
            "Config": {

            },
            "IsLocal": true,
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "DATETIME"
                    },
                    "AttributeName": "live_date"
                }
            ],
            "FromVertexTypeName": "User5",
            "Name": "edge1"
        }
    ],
    "dropEdgeTypes": [
        "e1"
    ],
    "alterEdgeTypes": [
        {
            "dropAttributes": [
                "attr1"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "name": "e2"
        }
    ]
}
'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created schema change job: [test5]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
|  yes
| the graph whose schema change job to create 

| `type`
| yes
| `local`, means create local schema change
|===

'''  
=== get a specific local/global schema change job

`GET /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test1?json=true&graph=empty_graph"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"test1":"CREATE GLOBAL SCHEMA_CHANGE JOB test1 {\n      ADD VERTEX user TO GRAPH empty_graph;\n    }\n"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
|  no
| the graph whose schema change job to show 

| `json`
| yes
| `true`, meann response format `json`, else `text`
|===

'''  
=== run global schema change job directly 

`POST /gsql/v1/schema/change`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/change" -d ' 
 {"addVertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User5"},
{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User4"}
]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created vertices: [User5, User4]."}
----
--
====
==== Parameters:

None

'''  
=== run local schema change job directly

`POST /gsql/v1/schema/change`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/change?graph=recommend" -d 
'{
    "dropVertexTypes": [
    ],
    "alterVertexTypes": [
        {
            "name": "house",
            "dropAttributes": [
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "dropIndexAttributes": [
                {
                    "indexName": "Index_Type_Name",
                    "attributeName": "area"
                },
                {
                    "indexName": "height_type_name",
                    "attributeName": "height"
                }
            ],
            "addIndexAttributes": [
                {
                    "indexName": "xIndex",
                    "attributeName": "x"
                },
                {
                    "indexName": "yIndex",
                    "attributeName": "y"
                }
            ]
        }
    ],
    "addVertexTypes": [
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User5"
        },
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User4"
        }
    ],
    "addEdgeTypes": [
        {
            "IsDirected": true,
            "ToVertexTypeName": "User4",
            "Config": {

            },
            "IsLocal": true,
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "DATETIME"
                    },
                    "AttributeName": "live_date"
                }
            ],
            "FromVertexTypeName": "User5",
            "Name": "edge1"
        }
    ],
    "dropEdgeTypes": [
    ],
    "alterEdgeTypes": [
        {
            "dropAttributes": [
                "attr1"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "name": "e1"
        }
    ]
}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Schema change job runs successfully"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph who the local schema change runs on
|===

'''  
=== run an existing schema change job

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test1?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Schema change job run successfully!"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph who the schema change job runs on
|===

'''  
=== get all local schema change jobs

`GET /gsql/v1/schema/jobs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"add2":{"dropVertexTypes":[],"addTags":[],"name":"add2","alterVertexTypes":[],"addVertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE","PRIMARY_ID_AS_ATTRIBUTE":true},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"lastName"},{"AttributeType":{"Name":"INT"},"AttributeName":"age"},{"AttributeType":{"Name":"DATETIME"},"AttributeName":"birthday"},{"AttributeType":{"Name":"FLOAT"},"AttributeName":"weight"},{"AttributeType":{"Name":"DOUBLE"},"AttributeName":"salary"},{"AttributeType":{"Name":"BOOL"},"AttributeName":"marriage"},{"AttributeType":{"ValueTypeName":"STRING","Name":"LIST"},"AttributeName":"speaks"},{"AttributeType":{"ValueTypeName":"STRING","Name":"SET"},"AttributeName":"email"},{"AttributeType":{"ValueTypeName":"STRING","KeyTypeName":"INT","Name":"MAP"},"AttributeName":"familyMember"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"test_person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE","PRIMARY_ID_AS_ATTRIBUTE":true},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"url"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"test_city"}],"addEdgeTypes":[{"IsDirected":true,"ToVertexTypeName":"test_city","Config":{},"Attributes":[{"AttributeType":{"Name":"DATETIME"},"AttributeName":"live_date"}],"FromVertexTypeName":"test_person","Name":"test_live_in"}],"dropEdgeTypes":[],"graph":"person_movie","alterEdgeTypes":[],"dropTags":[]}}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph whose schema change job to show

| `json`
| yes
| `true`, request format is `json`
|===

'''  

== Privilage

=== show all privilages

`GET /gsql/v1/privileges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices?graph=g"
{"error":false,"message":"","results":[{"privilegeType":"GRAPH","privilege":"READ_SCHEMA"},{"privilegeType":"GRAPH","privilege":"WRITE_SCHEMA"},{"privilegeType":"GRAPH","privilege":"READ_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"EXECUTE_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"WRITE_LOADINGJOB"},{"privilegeType":"QUERY","privilege":"READ_QUERY"},{"privilegeType":"GRAPH","privilege":"CREATE_QUERY"},{"privilegeType":"QUERY","privilege":"UPDATE_QUERY"},{"privilegeType":"QUERY","privilege":"DROP_QUERY"},{"privilegeType":"QUERY","privilege":"INSTALL_QUERY"},{"privilegeType":"QUERY","privilege":"EXECUTE_QUERY"},{"privilegeType":"QUERY","privilege":"OWNER"},{"privilegeType":"GRAPH","privilege":"WRITE_DATASOURCE"},{"privilegeType":"GRAPH","privilege":"READ_ROLE"},{"privilegeType":"GRAPH","privilege":"WRITE_ROLE"},{"privilegeType":"GRAPH","privilege":"READ_USER"},{"privilegeType":"GLOBAL","privilege":"WRITE_USER"},{"privilegeType":"GRAPH","privilege":"READ_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"WRITE_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"READ_FILE"},{"privilegeType":"GLOBAL","privilege":"WRITE_FILE"},{"privilegeType":"GLOBAL","privilege":"DROP_GRAPH"},{"privilegeType":"GLOBAL","privilege":"EXPORT_GRAPH"},{"privilegeType":"GLOBAL","privilege":"CLEAR_GRAPHSTORE"},{"privilegeType":"GLOBAL","privilege":"DROP_ALL"},{"privilegeType":"GRAPH","privilege":"ACCESS_TAG"},{"privilegeType":"GRAPH","privilege":"READ_DATA"},{"privilegeType":"GRAPH","privilege":"CREATE_DATA"},{"privilegeType":"GRAPH","privilege":"UPDATE_DATA"},{"privilegeType":"GRAPH","privilege":"DELETE_DATA"},{"privilegeType":"GRAPH","privilege":"APP_ACCESS_DATA"},{"privilegeType":"GRAPH","privilege":"READ_POLICY"},{"privilegeType":"GRAPH","privilege":"WRITE_POLICY"},{"privilegeType":"PACKAGE","privilege":"USE_FUNCTION"},{"privilegeType":"PACKAGE","privilege":"WRITE_FUNCTION"},{"privilegeType":"GLOBAL","privilege":"READ_WORKLOAD_QUEUE"},{"privilegeType":"GLOBAL","privilege":"WRITE_WORKLOAD_QUEUE"}]}
----

===== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''
