= GSQL Endpoints
:pp: {plus}{plus}
:description: A set of GSQL REST API endpoints about vertex in TigerGraph server.
:toc:

This page describes the REST API endpoints accessible on a TigerGraph server.

[NOTE]
====
*Note for users of TigerGraph Cloud*

For all TigerGraph Cloud solutions created on or after June 20, 2022, ports 14240 and 9000 are no longer exposed.
This also applies to previously created cloud solutions that are resized on or after June 20, 2022. Use port 443 instead for API endpoint connectivity on cloud solutions:

** Use API endpoint `443/restpp/<endpoint>` for RESTPP endpoints that were on port 9000

** Use API endpoint `443/<endpoint>` for endpoints that were on port 14240

For all TigerGraph Server solutions not on TigerGraph Cloud, or for TigerGraph Cloud solutions created before June 20, 2022, ports 9000 and 14240 remain correct.
====

== Schema

=== show local vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices?graph=g"
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----

===== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''
=== show all global vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices"
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"uid"},"Name":"user"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"wid"},"Name":"website"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"pid"},"Name":"product"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user2"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"DATETIME"},"AttributeName":"dob"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user3"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----

==== Parameters:

None

'''
=== show a local vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices/house Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/house?graph=g"
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"IsLocal":true,"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"house"}}
----

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''        
=== show a global vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices/person Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/person"
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"}}
----

==== Parameters:

NONE

'''     

=== create vertex usgin gsql command 

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/vertices?gsql=true" -d '{"gsql":["CREATE VERTEX UserA (PRIMARY_ID user_id UINT, name STRING)", "CREATE VERTEX UserB (PRIMARY_ID user_id UINT, name STRING)"]}'
{"error":false,"message":"Successfully create vertices: [UserA, UserB]"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== create vertex (add global vertex to local graph)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false&graph=empty_graph" -d '{"addVertices":["user","website"]}'
{"error":false,"message":"Successfully add vertices: [user, website] on graph empty_graph"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create vertex (create vertex in global level)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false" -d '{"createVertices":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User5"},
{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User4"}
]}'
{"error":false,"message":"Successfully create vertices: [User5, User4]"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3"
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dorp all the vertices
|===

'''  

=== drop local vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3&graph=recommend"
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dropping all the vertices

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  

=== drop a local vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/vertices/user2 Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2?graph=recommend"
{"error":false,"message":"Vertices [user2] deleted successfully."}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to be deleted
|===


'''  
=== drop a global vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/vertices/user2 Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2"
{"error":false,"message":"Vertices [user2] deleted successfully."}
----

==== Parameters:

None

'''  
=== update vertex attribute (local graph)

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.PUT /gsql/v1/schema/vertices/user Request and Response

[source,console]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user?graph=recommend" -d '{"dropAttributes":["area"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr1"}]}'
{"error":false,"message":"Successfully update vertex: user"}
----

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to update
|===

'''  
=== update a global vertex attribute

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.PUT /gsql/v1/schema/vertices/user Request and Response

[source,console]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
{"error":false,"message":"Successfully update vertex: user"}
----

==== Parameters:

None

=== get all global edges 

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges"
{"error":false,"message":"","results":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"},{"IsDirected":true,"ToVertexTypeName":"website","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"has_account"},{"IsDirected":false,"ToVertexTypeName":"website","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"item_id"}],"FromVertexTypeName":"product","Name":"sell_on"},{"IsDirected":true,"ToVertexTypeName":"product","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"viewed"},{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----

==== Parameters:

None

'''
=== get all edges in graph

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges?graph=person_movie"
{"error":false,"message":"","results":[{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===

'''
=== get a global specific edge type info

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/edges/purchase Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/purchase"
{"error":false,"message":"","results":{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"}}
----

==== Parameters:

None

'''        
=== get a specific edge type info (under graph)

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/edges/roles Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/roles?graph=person_movie"
{"error":false,"message":"","results":{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===


'''     

=== create edges using gsql command statement

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/edges?gsql=true" -d '{"gsql":["CREATE UNDIRECTED EDGE edge1 (from user3, to product, attr1 float)", "CREATE UNDIRECTED EDGE edge2 (from user2, to product, attr2 float)"]}'
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== add global edges to graph using json format

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false&graph=empty_graph" -d '{"addEdges":["has_account"]}'
{"error":true,"message":"Failed to create edges [has_account]. Semantic Check Fails: The schema change job tries to add edge has_account to graph empty_graph, but the FROM vertex type user does not exist on the graph.\n"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create global edges using json format 

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.POST /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false" -d ' {"createEdges":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr1"}],"FromVertexTypeName":"user3","Name":"edge1"},{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr2"}],"FromVertexTypeName":"user2","Name":"edge2"}]}'
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global edges

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=test1"
{"error":false,"message":"Successfully dropped edges: [test1]."}
----

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|===

'''  

=== drop edges from graph

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/edges Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=e1&graph=recommend"
{"error":false,"message":"Edges [e1] deleted successfully."}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  
=== drop an local edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/edges/e1 Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend"
{"error":false,"message":"Edges [e1] deleted successfully."}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be deleted
|===


'''  
=== drop a global edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.DELETE /gsql/v1/schema/edges/test1 Request and Response

[source,console]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/test1"
{"error":false,"message":"Successfully dropped edges: [test1]."}
----

==== Parameters:

None

'''  
=== update attribute in edge in global level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.PUT /gsql/v1/schema/edges/purchase Request and Response

[source,console]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/purchase" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
{"error":false,"message":"Successfully update edge: purchase"}
----

==== Parameters:

None

'''  
=== update attribute in edge in local level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.PUT /gsql/v1/schema/edges/e1 Request and Response

[source,console]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
{"error":false,"message":"Successfully update edge: e1"}
----

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be update
|===


'''  
== Privilage

=== show all privilages

`GET /gsql/v1/privileges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Sample request:

.GET /gsql/v1/schema/vertices Request and Response

[source,console]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices?graph=g"
{"error":false,"message":"","results":[{"privilegeType":"GRAPH","privilege":"READ_SCHEMA"},{"privilegeType":"GRAPH","privilege":"WRITE_SCHEMA"},{"privilegeType":"GRAPH","privilege":"READ_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"EXECUTE_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"WRITE_LOADINGJOB"},{"privilegeType":"QUERY","privilege":"READ_QUERY"},{"privilegeType":"GRAPH","privilege":"CREATE_QUERY"},{"privilegeType":"QUERY","privilege":"UPDATE_QUERY"},{"privilegeType":"QUERY","privilege":"DROP_QUERY"},{"privilegeType":"QUERY","privilege":"INSTALL_QUERY"},{"privilegeType":"QUERY","privilege":"EXECUTE_QUERY"},{"privilegeType":"QUERY","privilege":"OWNER"},{"privilegeType":"GRAPH","privilege":"WRITE_DATASOURCE"},{"privilegeType":"GRAPH","privilege":"READ_ROLE"},{"privilegeType":"GRAPH","privilege":"WRITE_ROLE"},{"privilegeType":"GRAPH","privilege":"READ_USER"},{"privilegeType":"GLOBAL","privilege":"WRITE_USER"},{"privilegeType":"GRAPH","privilege":"READ_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"WRITE_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"READ_FILE"},{"privilegeType":"GLOBAL","privilege":"WRITE_FILE"},{"privilegeType":"GLOBAL","privilege":"DROP_GRAPH"},{"privilegeType":"GLOBAL","privilege":"EXPORT_GRAPH"},{"privilegeType":"GLOBAL","privilege":"CLEAR_GRAPHSTORE"},{"privilegeType":"GLOBAL","privilege":"DROP_ALL"},{"privilegeType":"GRAPH","privilege":"ACCESS_TAG"},{"privilegeType":"GRAPH","privilege":"READ_DATA"},{"privilegeType":"GRAPH","privilege":"CREATE_DATA"},{"privilegeType":"GRAPH","privilege":"UPDATE_DATA"},{"privilegeType":"GRAPH","privilege":"DELETE_DATA"},{"privilegeType":"GRAPH","privilege":"APP_ACCESS_DATA"},{"privilegeType":"GRAPH","privilege":"READ_POLICY"},{"privilegeType":"GRAPH","privilege":"WRITE_POLICY"},{"privilegeType":"PACKAGE","privilege":"USE_FUNCTION"},{"privilegeType":"PACKAGE","privilege":"WRITE_FUNCTION"},{"privilegeType":"GLOBAL","privilege":"READ_WORKLOAD_QUEUE"},{"privilegeType":"GLOBAL","privilege":"WRITE_WORKLOAD_QUEUE"}]}
----

===== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''
