= GSQL Endpoints
:pp: {plus}{plus}
:description: A set of GSQL REST API endpoints about vertex in TigerGraph server.
:toc:

This page describes the REST API endpoints accessible on a TigerGraph server.

[NOTE]
====
*Note for users of TigerGraph Cloud*

For all TigerGraph Cloud solutions created on or after June 20, 2022, ports 14240 and 9000 are no longer exposed.
This also applies to previously created cloud solutions that are resized on or after June 20, 2022. Use port 443 instead for API endpoint connectivity on cloud solutions:

** Use API endpoint `443/restpp/<endpoint>` for RESTPP endpoints that were on port 9000

** Use API endpoint `443/<endpoint>` for endpoints that were on port 14240

For all TigerGraph Server solutions not on TigerGraph Cloud, or for TigerGraph Cloud solutions created before June 20, 2022, ports 9000 and 14240 remain correct.
====

== Schema

=== show local vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.


==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices?graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''
=== show all global vertices

`GET /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"uid"},"Name":"user"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"wid"},"Name":"website"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"pid"},"Name":"product"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user2"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"DATETIME"},"AttributeName":"dob"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"user3"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}]}
----
--
====

==== Parameters:

None

'''
=== show a local vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/house?graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"IsLocal":true,"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"house"}}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertices on which graph.
|===

'''        
=== show a global vertex

`GET /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/vertices/person"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"}}
----
--
====

==== Parameters:

NONE

'''     

=== create vertex usgin gsql command 

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/vertices?gsql=true" -d '{"gsql":["CREATE VERTEX UserA (PRIMARY_ID user_id UINT, name STRING)", "CREATE VERTEX UserB (PRIMARY_ID user_id UINT, name STRING)"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create vertices: [UserA, UserB]"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== create vertex (add global vertex to local graph)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false&graph=empty_graph" -d '{"addVertices":["user","website"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully add vertices: [user, website] on graph empty_graph"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create vertex (create vertex in global level)

`POST /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices?gsql=false" -d '{"createVertices":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User5"},
{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User4"}
]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create vertices: [User5, User4]"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dorp all the vertices
|===

'''  

=== drop local vertices

`DELETE /gsql/v1/schema/vertices`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices?vertexName=user2,user3&graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2, user3] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertexName`
| yes
| the vertex types to be delete, if there exist more than one, use , separate it. value all means dropping all the vertices

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  

=== drop a local vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to be deleted
|===


'''  
=== drop a global vertex

`DELETE /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/vertices/user2"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Vertices [user2] deleted successfully."}
----
--
====
==== Parameters:

None

'''  
=== update vertex attribute (local graph)

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user?graph=recommend" -d '{"dropAttributes":["area"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr1"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update vertex: user"}
----
--
====
==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the vertex in which graph to update
|===

'''  
=== update a global vertex attribute

`PUT /gsql/v1/schema/vertices/{vertexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/vertices/user" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update vertex: user"}
----
--
====
==== Parameters:

None

'''  
===  show all indexes
`GET /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"person":[{"index":"canSpeak_index","attribute":"canSpeak"}]}]}
----
--
====
==== Parameters:

None

'''  
=== show all indexes on a graph
`GET /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=recommend" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"house":[{"index":"height_type_name","attribute":"height"},{"index":"Index_Type_Name","attribute":"area"}]}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the indexes in which graph to show
|===

'''  
=== show an index
`GET /gsql/v1/schema/indexes/{indexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes/Index_Type_Name?graph=recommend" 
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"index":"Index_Type_Name","attribute":"area"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the indexes in which graph to show
|===

'''  
=== create indexes
`POST /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=recommend" -d '{"vertex":"house","addIndexAttributes":[{"indexName":"areaIndex","attributeName":"area"},{"indexName":"heightIndex","attributeName":"height"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully add index areaIndex on attribute area\nSuccessfully add index heightIndex on attribute height\n"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the indexes in which graph to create
|===

'''  
=== drop an index
`DELETE /gsql/v1/schema/indexes/{indexName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?vertex=name1&graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully drop index"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertex`
| yes
| the vertex on which to drop index

| `graph`
| no
| the indexes in which graph to drop
|===

'''  
=== drop indexes
`DELETE /gsql/v1/schema/indexes`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/indexes?graph=g&vertex=name1 &indexName=index1,index2"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully drop index"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `vertex`
| yes
| the vertex on which to drop index

| `indexName`
| yes
| the indexes to drop (seperate by ,)

| `graph`
| no
| the indexes in which graph to drop
|===

'''  
=== get all global edges 

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"},{"IsDirected":true,"ToVertexTypeName":"website","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"has_account"},{"IsDirected":false,"ToVertexTypeName":"website","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"item_id"}],"FromVertexTypeName":"product","Name":"sell_on"},{"IsDirected":true,"ToVertexTypeName":"product","Config":{},"Attributes":[],"FromVertexTypeName":"user","Name":"viewed"},{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----
--
====
==== Parameters:

None

'''
=== get all edges in graph

`GET /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===

'''
=== get a global specific edge type info

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/purchase"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"transaction_id"}],"FromVertexTypeName":"user","Name":"purchase"}}
----
--
====
==== Parameters:

None

'''        
=== get a specific edge type info (under graph)

`GET /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/schema/edges/roles?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edges in which graph 
|===


'''     

=== create edges using gsql command statement

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "http://localhost:14240/gsql/v1/schema/edges?gsql=true" -d '{"gsql":["CREATE UNDIRECTED EDGE edge1 (from user3, to product, attr1 float)", "CREATE UNDIRECTED EDGE edge2 (from user2, to product, attr2 float)"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be true, means gsql command foramt
|===


'''     

=== add global edges to graph using json format

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false&graph=empty_graph" -d '{"addEdges":["has_account"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":true,"message":"Failed to create edges [has_account]. Semantic Check Fails: The schema change job tries to add edge has_account to graph empty_graph, but the FROM vertex type user does not exist on the graph.\n"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format

| `graph`
| yes
| which graph the global vertex to be added
|===

'''   
=== create global edges using json format 

`POST /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges?gsql=false" -d ' {"createEdges":[{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr1"}],"FromVertexTypeName":"user3","Name":"edge1"},{"IsDirected":false,"ToVertexTypeName":"product","Config":{},"Attributes":[{"AttributeType":{"Name":"FLOAT"},"AttributeName":"attr2"}],"FromVertexTypeName":"user2","Name":"edge2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully create edges: [edge1, edge2]"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| this should be false, means a json format
|===

'''  

=== drop global edges

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=test1"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped edges: [test1]."}
----
--
====

==== Parameters:
//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|===

'''  

=== drop edges from graph

`DELETE /gsql/v1/schema/edges`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges?edgeName=e1&graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Edges [e1] deleted successfully."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `edgeName`
| yes
| the edge types to be delete, if there exist more than one, use `,` separate; value all means drop all the edges
|

| `graph`
| yes
| the vertices in which graph to be deleted
|===

'''  
=== drop an local edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Edges [e1] deleted successfully."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be deleted
|===


'''  
=== drop a global edge

`DELETE /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/edges/test1"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped edges: [test1]."}
----
--
====

==== Parameters:

None

'''  
=== update attribute in edge in global level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/purchase" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update edge: purchase"}
----
--
====
==== Parameters:

None

'''  
=== update attribute in edge in local level

`PUT /gsql/v1/schema/edges/{edgeName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/edges/e1?graph=recommend" -d '{"dropAttributes":["attr1"],"addAttributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"attr2"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully update edge: e1"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the edge in which graph to be update
|===


'''  
=== show all graphs info only containing names of vertices and edges

`GET /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs"
----
--
Response::
+
--
[source.wrap,console]
----
{"graphs":[{"graphName":"recommend","vertices":["user","website","product","user2","user3"],"edges":["purchase","has_account","sell_on","viewed"]},{"graphName":"person_movie","vertices":["person","movie"],"edges":["roles","roles2"]}],"error":false,"message":""}
----
--
====
==== Parameters:

None

'''  
=== show one graph detailed info with given graph name


`GET /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?graphName=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----

{"error":false,"message":"","results":{"GraphName":"person_movie","VertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"UINT"},"AttributeName":"sid"},{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"title"},{"AttributeType":{"Name":"STRING COMPRESS"},"AttributeName":"country"},{"AttributeType":{"Name":"UINT"},"AttributeName":"year"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"movie"}],"EdgeTypes":[{"IsDirected":true,"ToVertexTypeName":"movie","Config":{"REVERSE_EDGE":"roles2"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"role"}],"FromVertexTypeName":"person","Name":"roles"}]}}
 
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph whose schema to show
|===

=== create one graph using gsql command


`POST /gsql/v1/schema/graphs?gsql=true`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?gsql=true" -d '{"gsql": "create graph g(*)"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created graph: [g]."} 
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| true, means using gsql command
|===

'''  

=== create one graph using JSON format 

`POST /gsql/v1/schema/graphs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/graphs?graphName=gtest&gsql=false
" -d '{"VertexTypes":["user","product"], "EdgeTypes":["purchase"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created graph: [gtest]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| false, means using JSON

| `graphName`
| yes
| the graph name
|===

'''  

=== drop one graph

`DELETE /gsql/v1/schema/graphs/{graphName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/graphs/person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped graph: person_movie."}
----
--
====
==== Parameters:

None

'''  

=== drop graphs with given names

`DELETE /gsql/v1/schema/graphs/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/graphs?graphNames=person_movie,recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped graphs: [person_movie, recommend]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graphNames`
| yes
| the graph names(separate by `,`), all means drop all the graphs
|===

'''  
=== drop local/global scheme change job

`DELETE /gsql/v1/schema/jobs/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/jobs?jobName=test1,test2&graph=g"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped schema change jobs: [test1, test2]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `jobName`
| yes
| the schema jobs to drop (separate by `,`) 

| `graph`
| no
| the graph whose jobs to drop.
|===

'''  
=== create local/global scheme change job using gsql command

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/jobs/test3?gsql=true&type=global" -d ' {"gsql" : "create global schema_change job test3 {add vertex website to graph person_movie;}"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created global schema change job: [test3]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| yes
| `true`, means using gsql command

| `type`
| yes
| when `global` means create global schema change, `local` means create local schema change.
|===

'''  
=== create global scheme change job using json

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test4?gsql=false&type=global" -d '{"graphs": [{"graphName":"empty_graph","addVertexTypes":["user","website"],"dropVertexTypes":[], "dropEdgeTypes":[],"addEdgeTypes":[]}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created global schema change job: [test4]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsql`
| false
| `true`, means post body using json 

| `type`
| yes
| `global`, means create global schema change
|===

'''  
=== create local scheme change job using json

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test5?type=local&graph=recommend" -d 
'{
    "dropVertexTypes": [
        "desk"
    ],
    "alterVertexTypes": [
        {
            "name": "house",
            "dropAttributes": [
                "height"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "dropIndexAttributes": [
                {
                    "indexName": "Index_Type_Name",
                    "attributeName": "area"
                }
            ],
            "addIndexAttributes": [
                {
                    "indexName": "ppIndex",
                    "attributeName": "pp"
                }
            ]
        }
    ],
    "addVertexTypes": [
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User5"
        },
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User4"
        }
    ],
    "addEdgeTypes": [
        {
            "IsDirected": true,
            "ToVertexTypeName": "User4",
            "Config": {

            },
            "IsLocal": true,
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "DATETIME"
                    },
                    "AttributeName": "live_date"
                }
            ],
            "FromVertexTypeName": "User5",
            "Name": "edge1"
        }
    ],
    "dropEdgeTypes": [
        "e1"
    ],
    "alterEdgeTypes": [
        {
            "dropAttributes": [
                "attr1"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "name": "e2"
        }
    ]
}
'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created schema change job: [test5]."}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
|  yes
| the graph whose schema change job to create 

| `type`
| yes
| `local`, means create local schema change
|===

'''  
=== get a specific local/global schema change job

`GET /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test1?json=true&graph=empty_graph"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"test1":"CREATE GLOBAL SCHEMA_CHANGE JOB test1 {\n      ADD VERTEX user TO GRAPH empty_graph;\n    }\n"}}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
|  no
| the graph whose schema change job to show 

| `json`
| yes
| `true`, meann response format `json`, else `text`
|===

'''  
=== run global schema change job directly 

`POST /gsql/v1/schema/change`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/change" -d ' 
 {"addVertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User5"},
{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE"},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"name"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"user_id"},"Name":"User4"}
]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created vertices: [User5, User4]."}
----
--
====
==== Parameters:

None

'''  
=== run local schema change job directly

`POST /gsql/v1/schema/change`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/change?graph=recommend" -d 
'{
    "dropVertexTypes": [
    ],
    "alterVertexTypes": [
        {
            "name": "house",
            "dropAttributes": [
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "dropIndexAttributes": [
                {
                    "indexName": "Index_Type_Name",
                    "attributeName": "area"
                },
                {
                    "indexName": "height_type_name",
                    "attributeName": "height"
                }
            ],
            "addIndexAttributes": [
                {
                    "indexName": "xIndex",
                    "attributeName": "x"
                },
                {
                    "indexName": "yIndex",
                    "attributeName": "y"
                }
            ]
        }
    ],
    "addVertexTypes": [
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User5"
        },
        {
            "Config": {
                "STATS": "OUTDEGREE_BY_EDGETYPE"
            },
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "name"
                }
            ],
            "PrimaryId": {
                "AttributeType": {
                    "Name": "UINT"
                },
                "AttributeName": "user_id"
            },
            "Name": "User4"
        }
    ],
    "addEdgeTypes": [
        {
            "IsDirected": true,
            "ToVertexTypeName": "User4",
            "Config": {

            },
            "IsLocal": true,
            "Attributes": [
                {
                    "AttributeType": {
                        "Name": "DATETIME"
                    },
                    "AttributeName": "live_date"
                }
            ],
            "FromVertexTypeName": "User5",
            "Name": "edge1"
        }
    ],
    "dropEdgeTypes": [
    ],
    "alterEdgeTypes": [
        {
            "dropAttributes": [
                "attr1"
            ],
            "addAttributes": [
                {
                    "DefaultValue": "defaultValue1",
                    "AttributeType": {
                        "Name": "STRING"
                    },
                    "AttributeName": "attr2"
                }
            ],
            "name": "e1"
        }
    ]
}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Schema change job runs successfully"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph who the local schema change runs on
|===

'''  
=== run an existing schema change job

`POST /gsql/v1/schema/jobs/{jobName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs/test1?graph=recommend"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Schema change job run successfully!"}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph who the schema change job runs on
|===

'''  
=== get all local schema change jobs

`GET /gsql/v1/schema/jobs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs?graph=person_movie"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"add2":{"dropVertexTypes":[],"addTags":[],"name":"add2","alterVertexTypes":[],"addVertexTypes":[{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE","PRIMARY_ID_AS_ATTRIBUTE":true},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"lastName"},{"AttributeType":{"Name":"INT"},"AttributeName":"age"},{"AttributeType":{"Name":"DATETIME"},"AttributeName":"birthday"},{"AttributeType":{"Name":"FLOAT"},"AttributeName":"weight"},{"AttributeType":{"Name":"DOUBLE"},"AttributeName":"salary"},{"AttributeType":{"Name":"BOOL"},"AttributeName":"marriage"},{"AttributeType":{"ValueTypeName":"STRING","Name":"LIST"},"AttributeName":"speaks"},{"AttributeType":{"ValueTypeName":"STRING","Name":"SET"},"AttributeName":"email"},{"AttributeType":{"ValueTypeName":"STRING","KeyTypeName":"INT","Name":"MAP"},"AttributeName":"familyMember"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"test_person"},{"Config":{"STATS":"OUTDEGREE_BY_EDGETYPE","PRIMARY_ID_AS_ATTRIBUTE":true},"Attributes":[{"AttributeType":{"Name":"STRING"},"AttributeName":"url"}],"PrimaryId":{"AttributeType":{"Name":"UINT"},"AttributeName":"id"},"Name":"test_city"}],"addEdgeTypes":[{"IsDirected":true,"ToVertexTypeName":"test_city","Config":{},"Attributes":[{"AttributeType":{"Name":"DATETIME"},"AttributeName":"live_date"}],"FromVertexTypeName":"test_person","Name":"test_live_in"}],"dropEdgeTypes":[],"graph":"person_movie","alterEdgeTypes":[],"dropTags":[]}}]}
----
--
====
==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| the graph whose schema change job to show

| `json`
| yes
| `true`, request format is `json`
|===

'''  
=== get all global schema change jobs

`GET /gsql/v1/schema/jobs`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "content-type: application/json" "http://localhost:14240/gsql/v1/schema/jobs"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"test1":"CREATE GLOBAL SCHEMA_CHANGE JOB test1 {\n      ADD VERTEX user TO GRAPH empty_graph;\n    }\n"},{"test2":"CREATE GLOBAL SCHEMA_CHANGE JOB test2 {\n      ADD VERTEX product TO GRAPH empty_graph;\n    }\n"}]}
----
--
====
==== Parameters:

None

'''  


== Data source

=== get a data source

`GET /gsql/v1/data-sources/{dsName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/data-sources/k1"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"name":"k1","type":"KAFKA","content":{"broker":"kafka-0.tigergraph.com","kafka_config":{"security.protocol":"SSL"}}}}
----
--
====
===== Parameters:

None

'''

=== get all data sources

`GET /gsql/v1/data-sources`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/data-sources"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"name":"s1","belongTo":"empty_graph","type":"S3","content":{"access.key":"AKIA6B6T6R52UU7XJ2NL","secret.key":"","type":"s3"},"isLocal":true},{"name":"s2","belongTo":"person_movie","type":"S3","content":{"access.key":"AKIA6B6T6R52UU7XJ2NL","secret.key":"","type":"s3"},"isLocal":true},{"name":"k1","type":"KAFKA","content":{"broker":"kafka-0.tigergraph.com","kafka_config":{"security.protocol":"SSL"}},"isLocal":false}]}
----
--
====
===== Parameters:

None

'''
=== update data source 

`PUT /gsql/v1/data-sources`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT 'Content-type: application/json' "http://localhost:14240/gsql/v1/data-sources/s5?graph=g" -d '{"name":"s5","config":{"type":"s3","access.key":"AKIA6B6T6R52UU7XJ2NL","secret.key":""}}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Data source s5 is created"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph whose data source to update
|===

'''
=== create data source 

`POST /gsql/v1/data-sources`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST 'Content-type: application/json' "http://localhost:14240/gsql/v1/data-sources?graph=g" -d '{"name":"s4","config":{"type":"s3","access.key":"AKIA6B6T6R52UU7XJ2NL","secret.key":""}}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Data source s4 is created"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph whose data source to create
|===

'''
=== drop one data source 

`DELETE /gsql/v1/data-sources/{dsName}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE 'Content-type: application/json' "http://localhost:14240/gsql/v1/data-sources/k1?graph=g" -d '{"error":false,"message":"Data source k1 is dropped."}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Data source k1 is dropped."}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph whose data source to delete
|===

'''
=== grant one data source 

`POST /gsql/v1/data-sources/grant`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST 'Content-type: application/json' "http://localhost:14240/gsql/v1/data-sources/grant" -d '{"graphs":["empty_graph","person_movie"],"datasource":"k1"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully grant datasource k1 to the graph(s) [empty_graph, person_movie]"}
----
--
====
===== Parameters:

None

'''
=== revoke datasource 

`POST /gsql/v1/data-sources/revoke`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST 'Content-type: text/plain' "http://localhost:14240/gsql/v1/data-sources/revoke" -d '{"graphs":["empty_graph","person_movie"],"datasource":"k1"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully revoke datasource k1 from graph(s) [empty_graph, person_movie]"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph whose data source to revoke
|===

'''
=== drop all data source 

`DELETE /gsql/v1/data-sources/dropAll`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE 'Content-type: text/plain' "http://localhost:14240/gsql/v1/data-sources/dropAll"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"All data sources is dropped successfully."}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| the graph whose data sources to delete
|===

'''
=== get the sample data of S3 file.uris or local files

`POST /gsql/v1/sample-data`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST 'Content-type: application/json' "http://localhost:14240/gsql/v1/sample-data" -d ' 
 {
  "graphName": "ldbc_snb",
  "dataSource": "adsafsfsfsfds",
  "type": "s3",
  "path": "s3a://gsql-sample-data/test-json/test.json",
  "dataFormat": "json",
  "parsing": {
    "fileFormat": "none",
    "eol": "\\n"
  },
  "filling": "N/A",
  "size": 10
}'
----
--
Response::
+
--
[source.wrap,console]
----
{
    "error": false,
    "message": "",
    "results": {
        "data": [
            {
                "age": 40,
                "gender": "male",
                "name": "Tom",
                "state": "ca"
            },
            {
                "age": 34,
                "gender": "male",
                "name": "Dan",
                "state": "ny"
            },
            {
                "age": 25,
                "gender": "female",
                "name": "Jenny",
                "state": "tx"
            },
            [
                {
                    "age": 28,
                    "gender": "male",
                    "name": "Kevin",
                    "state": "az"
                },
                {
                    "age": 22,
                    "gender": "female",
                    "name": "Amily",
                    "state": "ca"
                },
                {
                    "age": 20,
                    "gender": "female",
                    "name": "Nancy",
                    "state": "ky"
                }
            ],
            {
                "age": 26,
                "gender": "male",
                "name": "Jack",
                "state": "fl"
            },
            {
                "age": 8,
                "gender": "male",
                "name": "a",
                "state": "OR"
            },
            {
                "age": 57,
                "gender": "male",
                "name": "aa",
                "state": "MA"
            },
            {
                "age": 25,
                "gender": "male",
                "name": "aaa",
                "state": "MI"
            },
            {
                "age": 71,
                "gender": "female",
                "name": "ab",
                "state": "WY"
            },
            {
                "age": 71,
                "gender": "female",
                "name": "abandoned",
                "state": "KS"
            }
        ],
        "header": [],
        "json": true
    }
}
----
--
====
===== Parameters:

None

'''
=== get all buckets of given S3 data source

`GET /gsql/v1/list-buckets/{s3Name}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET 'Content-type: text/plain' "http://localhost:14240/gsql/v1/list-buckets/abcd"
----
--
Response::
+
--
[source.wrap,console]
----
"error":false,"message":"","results":["acxiom2019","antifraudtg","aws-cloudtrail-logs-966275272565-4bde22f6","aws-glue-assets-966275272565-us-east-1","aws-logs-966275272565-us-east-1","bofa-louvain","ces-bucket-2","ces-neptune-bucket","ces-new-bucket","cf-templates-58ygac5qoly7-us-east-1","cloud-gbar-test","config-bucket-966275272565","databricks-workspace-stack-aa423-lambdazipsbucket-xjxhu6ikq892","databricks-workspace-stack-f31e4-bucket","databricks-workspace-stack-f31e4-lambdazipsbucket-ucd8ilhr3buv","databricks-workspace-stack-lambdazipsbucket-1qcpzmo9f4qzv","databricks-workspace-stack-lambdazipsbucket-1tycaofagn975","db-0cb8f9da9d4e67f9345947c4c54a5c3e-s3-root-bucket","db-81dc2edb4436079cea7c8c522f2ca24c-s3-root-bucket","db-ed2852b62420a6b838035944365a583a-s3-root-bucket","docker-image-store","docker-registry-backup","faerskit","faq.graphtiger.com","fareshealthcare","files.graphtiger.com","finfraud-demo-files","gbar-test","graphsql","graphsql-ctrip","graphsql-download","graphsql-elb-log","graphsql-eric-elb-log","graphsql-s3download","graphsql-test","graphsql-testdrive","graphsql-web","graphsql-xyz","graphsql-yeepay","graphstudio-customerportal","graphstudio-s3-e2e-test","graphstudio-sample-data-e2e-test","gsql-sample-data","kafka-connector-experiment","ldbc1","like-elb-test","litong","loading-test","merklescience","movie-rec-demo","pmitigergraph","presalesdocs","presalestg","racsftp","release-download-access-log","release-package-stats","release.graphtiger.com","renmaitong","rhfraud1","rik-bucket1","robb-tg-finfraud","robb-tgload-data","s3-import-test","s3-loading-test","se.training.deepdive","stevefuller-db","tango-test","test-gbar","test-graphstudio-bucket","test-s3import-el","test-website.graphtiger.com","tg-app-team","tg-isgs","tg-it-resource","tigergraph-aws-usage","tigergraph-benchmark-dataset","tigergraph-build-artifacts","tigergraph-cloudphysics","tigergraph-customer-support","tigergraph-development-artifects","tigergraph-download-hk","tigergraph-engineering-development-packages","tigergraph-fs-data","tigergraph-gle-prebuild","tigergraph-gui-prebuild-package","tigergraph-kafka-prebuild-package","tigergraph-mcafee-dlp","tigergraph-misc","tigergraph-release-download","tigergraph-release-prebuild","tigergraph-release-replica","tigergraph-temporary-files","tigergraph-test-dataset","tigergraph-testdrive-testdata","tigergraph-training","traininggsql","twitter-graph-benchmark","urbana-docker-ws","vladsynthea","xandrlog"]}
----
--
====
===== Parameters:

None

'''
=== get all files and directories under given S3 bucket path

`GET /gsql/v1/list-files/{s3Name}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET 'Content-type: text/plain' "http://localhost:14240/gsql/v1/list-files/fl2323?path=s3a://import-test"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"results":{"folders":["test-folder"],"files":["chinese.csv","movies.csv","ratings.csv","ratings.tar","ratings.tar.gz","ratings.zip",".csv"]}}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `path`
| no
| uri of the data source
|===

'''

== Database Utilities

=== backup

`GET /gsql/v1/internal/backup`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/internal/backup?path=/to/your/path"
----
--
Response::
+
--
[source.wrap,console]
----
{"gsql.replica":1,"error":false,"message":"The backup request finished successfully."}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `path`
| no
| the backup path
|===

'''
=== restore

`GET /gsql/v1/internal/restore`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/v1/internal/restore?path=/to/your/path&install=true&restore=true"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"The restore request finished successfully."}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `path`
| no
| the restore path

| `install`
| no
| `true`, force to install all queries

| `restore`
| no
| `true`, when use `gadmin backup restore` command;
|===


'''

=== recover gdict catalog

`POST /gsql/v1/schema/recover`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/recover"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Recover schema succeed!"}
----
--
====
==== Parameters:

None

'''  
=== validate graph schema

`POST /gsql/v1/schema/check`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "content-type: text/plain" "http://localhost:14240/gsql/v1/schema/check"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Schema Check succeeded."}
----
--
====
==== Parameters:

None

'''  

== Admin

=== retrieve a group by id using scim format

`GET /gsql/scim/v2/Groups/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/scim/v2/Groups/g2?gsqlFormat=false"
----
--
Response::
+
--
[source.wrap,console]
----
{"displayName":"g2","meta":{"location":"/scim/v2/Groups/54ba8a0f-693c-4cf3-9c53-5caaa244049a","resourceType":"Group"},"members":[],"id":"54ba8a0f-693c-4cf3-9c53-5caaa244049a"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `false`, using scim format; `true`, using gsql format;
|===

'''
<<<<<<< HEAD
=======

>>>>>>> 6df16c8... Update gsql-endpoints.adoc
=== retrieve a group by id using gsql format

`GET /gsql/scim/v2/Groups/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/scim/v2/Groups/g1?gsqlFormat=true"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"lastSuccessLogin":"Tue Jul 02 16:57:36 HKT 2024","privileges":{},"nextValidLogin":"Tue Jul 02 16:57:36 HKT 2024","roles":{},"failedAttempts":0,"members":[],"name":"g1","rule":"group=tech-department","disabled":false,"isSuperUser":false,"showAlterPasswordWarning":false,"secrets":[]}}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `true`, using gsql format
|===

'''

=== retrieve groups using gsql format

`GET /gsql/scim/v2/Groups/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "Content-type: text/plain" "http://localhost:14240/gsql/scim/v2/Groups?gsqlFormat=true"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"results":[{"lastSuccessLogin":"Tue Jul 02 17:07:50 HKT 2024","privileges":{},"nextValidLogin":"Tue Jul 02 17:07:50 HKT 2024","roles":{},"failedAttempts":0,"members":[],"name":"g1","rule":"group=tech-department","disabled":false,"isSuperUser":false,"showAlterPasswordWarning":false,"secrets":[]},{"lastSuccessLogin":"Tue Jul 02 17:07:50 HKT 2024","privileges":{},"nextValidLogin":"Tue Jul 02 17:07:50 HKT 2024","roles":{},"failedAttempts":0,"members":[],"name":"g2","rule":"group=tech-department","disabled":false,"isSuperUser":false,"showAlterPasswordWarning":false,"secrets":[]}]}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `true`, using gsql format
|===

'''

=== retrieve groups using scim format

`GET /gsql/scim/v2/Groups/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "Content-type: text/plain" "http://localhost:14240/gsql/scim/v2/Groups?excludedAttributes=members&gsqlFormat=false&filter=displayName%20nq%20'g2'%20and%20displayName%20sw%20'g1'"
----
--
Response::
+
--
[source.wrap,console]
----
{"totalResults":1,"startIndex":1,"itemsPerPage":100,"schemas":true,"Resources":[{"displayName":"g1","meta":{"location":"/scim/v2/Groups/0570fc42-79ea-427e-aa2e-2b53a0470163","resourceType":"Group"},"id":"0570fc42-79ea-427e-aa2e-2b53a0470163"}]}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| gsqlFormat
| yes
| Indicates whether to use the scim format. Value: false.

| filter
| yes
| The format should adhere to the structure: `displayName op {value} op2 displayName op {value}`. Here, `op` can be one of `eq`, `nq`, `co`, `sw`, `ew`, and `op2` can be either `and` or `or`.

| excludedAttributes
| yes
| Specifies attributes to be excluded. Currently supports only `members`.
|===

'''

=== create group using scim format

`POST /gsql/scim/v2/Groups/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Groups?gsqlFormat=false" -d '{"displayName":"scimG3","schemas":"[\"urn:ietf:params:scim:schemas:core:2.0:Group\"]","members":[{"display":"user3"},{"value":"user4"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"displayName":"scimG3","meta":{"location":"/scim/v2/Groups/706d0ad6-2165-4190-8512-de5abfd06988","resourceType":"Group"},"members":[{"display":"user3","type":"User","value":"16c1e6cc-3b2a-4d57-9a2e-fb55a5d14804"},{"display":"user4","type":"User","value":"457b9982-d5fb-4ad6-b50a-266919bf0c16"}],"id":"706d0ad6-2165-4190-8512-de5abfd06988"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| gsqlFormat
| yes
| Indicates whether to use the scim format. Value: false.
|===

'''
=== create group using gsql format

`POST /gsql/scim/v2/Groups/`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Groups?gsqlFormat=true" -d '{"groupName":"g4","proxyRule":"group=tech-department"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created group g4","results":{"lastSuccessLogin":"Tue Jul 02 17:32:40 HKT 2024","privileges":{},"nextValidLogin":"Tue Jul 02 17:32:40 HKT 2024","roles":{},"failedAttempts":0,"members":[],"name":"g4","rule":"group=tech-department","disabled":false,"isSuperUser":false,"showAlterPasswordWarning":false,"secrets":[]}}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| gsqlFormat
| yes
| Indicates whether to use the gsql format. Value: true.
|===

'''
=== update a group

`PATCH /gsql/scim/v2/Groups/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PATCH "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Groups/g1?gsqlFormat=false" -d ' 
{"schemas":"[\"urn:ietf:params:scim:api:messages:2.0:PatchOp\"]","Operations":[{"op":"remove","path":"members"},{"op":"replace","path":"members","value":[{"display":"user4"}]},{"op":"add","value":[{"display":"user3"}]}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"displayName":"g1","meta":{"location":"/scim/v2/Groups/0b181bc8-d055-4fcb-af52-20c560324c6f","resourceType":"Group"},"members":[{"display":"user3","type":"User","value":"5cdad092-af32-435e-9865-c2ad06b9d6f8"},{"display":"user4","type":"User","value":"c14765de-ea78-422a-bd87-88f3f7d3ceda"}],"id":"0b181bc8-d055-4fcb-af52-20c560324c6f"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| gsqlFormat
| yes
| Indicates whether to use the scim format. Value: false.
|===

'''
=== drop one group

`DELETE /gsql/scim/v2/Groups/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Groups/g1?gsqlFormat=false" -d ' 
{"schemas":"[\"urn:ietf:params:scim:api:messages:2.0:PatchOp\"]","Operations":[{"op":"remove","path":"members"},{"op":"replace","path":"members","value":[{"display":"user4"}]},{"op":"add","value":[{"display":"user3"}]}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped group g1"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| gsqlFormat
| yes
| Indicates whether to use the scim format. Value: false. Indicates whether to use the GSQL format. Value: true. 
|===

'''

=== drop groups

`POST /gsql/scim/v2/Groups`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Groups?action=delete" -d '{"groupNames":["g1"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped groups: [g1]"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| action
| yes
| Indicates whether to delete the groups. Value: delete. 
|===

'''

== User

=== retrieve a user by id using scim/gsql format

`GET /gsql/scim/v2/Users/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET "http://localhost:14240/gsql/scim/v2/Users/u1?gsqlFormat=false"
----
--
Response::
+
--
[source.wrap,console]
----
{"meta":{"location":"/scim/v2/Users/1e224fd0-54eb-43c3-84d6-455ca3b6339d","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"name":{},"active":true,"id":"1e224fd0-54eb-43c3-84d6-455ca3b6339d","userName":"u1"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `false`, using scim format; `true`, using gsql format;
|===

'''
=== update a user

`PUT /gsql/scim/v2/Users/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X PUT -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users/u1?gsqlFormat=false"  -d '{"schemas":"[\"urn:ietf:params:scim:api:messages:2.0:PatchOp\"]","Operations":[{"op":"replace","path":"password","value":"newPassword"}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"meta":{"location":"/scim/v2/Users/1e224fd0-54eb-43c3-84d6-455ca3b6339d","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"name":{},"active":true,"id":"1e224fd0-54eb-43c3-84d6-455ca3b6339d","userName":"u1"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `false`, using scim format; `true`, using gsql format;
|===

'''
=== drop users

`POST /gsql/scim/v2/Users/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users/u1?gsqlFormat=false&action=delete"  -d ' {"userNames":["u1"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped users: [u1]"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `action`
| yes
| Indicating drop users, value: delete.

| `gsqlFormat`
| yes
| `false`, using scim format; `true`, using gsql format;
|===

'''

=== drop a user

`DELETE /gsql/scim/v2/Users/{id}`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X DELETE -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users/u1?gsqlFormat=true"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully dropped user u1"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `false`, using scim format; `true`, using gsql format;
|===

'''

=== create user using scim format

`POST /gsql/scim/v2/Users`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users?gsqlFormat=false" -d ' 
{"password":"12345678","schemas":"[\"urn:ietf:params:scim:schemas:core:2.0:User\"]","name":{"familyName":"f","givenName":"g"},"externalId":"externalId123","active":false,"userName":"scimUser2"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"meta":{"location":"/scim/v2/Users/d838c224-d1d6-4a07-b6b5-5c0aab43f0a6","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"active":true,"id":"d838c224-d1d6-4a07-b6b5-5c0aab43f0a6","userName":"scimUser2"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `false`, using scim format; 
|===

'''
=== create user using gsql format

`POST /gsql/scim/v2/Users`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X POST -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users?gsqlFormat=true" -d ' {"password":"tiger123","username":"user2"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully created user user2"}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `true`, using gsql format; 
|===

'''
=== retrieve users using scim format

`GET /gsql/scim/v2/Users`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users?filter=userName%20nq%20%22tigergraph%22%20and%20userName%20sw%20%22u%22&gsqlFormat=false&excludedAttributes=names"
----
--
Response::
+
--
[source.wrap,console]
----
{"totalResults":2,"startIndex":1,"itemsPerPage":100,"schemas":true,"Resources":[{"meta":{"location":"/scim/v2/Users/7a004538-8d41-4f85-b5e7-2a26358f0173","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"name":{},"active":true,"id":"7a004538-8d41-4f85-b5e7-2a26358f0173","userName":"tigergraph"},{"meta":{"location":"/scim/v2/Users/0a71523d-9623-4b04-908d-395096e288f4","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"name":{},"active":true,"id":"0a71523d-9623-4b04-908d-395096e288f4","userName":"u1"}]}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `excludedAttributes`
| no
| `names`, currently only support this value.

| filter
| yes
| The format should follow this pattern: `userName op {value} op2 displayName op {value}`. Here, `op` can be one of `eq`, `nq`, `co`, `sw`, `ew`, and `op2` can be either `and` or `or`. Example: 1. userName eq "user1" 2. userName sw "u" and userName nq "u1"

| `gsqlFormat`
| yes
| `false`, using scim format; 
|===

'''
=== retrieve users using gsql format

`GET /gsql/scim/v2/Users`

These endpoints are simple diagnostic utilities, which respond with the following message if the GSQL server is up and running.

==== Example
[,tabs]
====
Request::
+
--
[source,bash]
----
curl -X GET -H "Content-type: application/json" "http://localhost:14240/gsql/scim/v2/Users?gsqlFormat=true"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"results":[{"lastSuccessLogin":"Wed Jul 03 15:26:33 HKT 2024","privileges":{"1":{"privileges":["READ_SCHEMA","WRITE_SCHEMA","READ_LOADINGJOB","EXECUTE_LOADINGJOB","WRITE_LOADINGJOB","CREATE_QUERY","WRITE_DATASOURCE","READ_ROLE","WRITE_ROLE","READ_USER","WRITE_USER","READ_PROXYGROUP","WRITE_PROXYGROUP","READ_FILE","WRITE_FILE","DROP_GRAPH","EXPORT_GRAPH","CLEAR_GRAPHSTORE","DROP_ALL","ACCESS_TAG","READ_DATA","CREATE_DATA","UPDATE_DATA","DELETE_DATA","APP_ACCESS_DATA","READ_POLICY","WRITE_POLICY","USE_FUNCTION","WRITE_FUNCTION","READ_WORKLOAD_QUEUE","WRITE_WORKLOAD_QUEUE"]},"recommend":{"privileges":[]}},"nextValidLogin":"Wed Jul 03 15:26:33 HKT 2024","roles":{"1":["superuser"],"recommend":["superuser"]},"failedAttempts":0,"name":"tigergraph","disabled":false,"isSuperUser":true,"showAlterPasswordWarning":false,"secrets":[]},{"lastSuccessLogin":"Wed Jul 03 15:26:33 HKT 2024","privileges":{"recommend":{"privileges":[]}},"nextValidLogin":"Wed Jul 03 15:26:33 HKT 2024","roles":{"recommend":["r1"]},"failedAttempts":0,"name":"u1","disabled":false,"isSuperUser":false,"showAlterPasswordWarning":false,"secrets":[]}]}
----
--
====
===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `gsqlFormat`
| yes
| `true`, using gsql format; 
|===

'''

<<<<<<< HEAD
== Privilage
=======
'''  

== Admin
>>>>>>> 19b4ad5... Update gsql-endpoints.adoc

=== show all privilages

`GET /gsql/v1/privileges`

This endpoint is used to list all built-in privileges.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET "http://localhost:14240/gsql/v1/privileges"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":[{"privilegeType":"GRAPH","privilege":"READ_SCHEMA"},{"privilegeType":"GRAPH","privilege":"WRITE_SCHEMA"},{"privilegeType":"GRAPH","privilege":"READ_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"EXECUTE_LOADINGJOB"},{"privilegeType":"GRAPH","privilege":"WRITE_LOADINGJOB"},{"privilegeType":"QUERY","privilege":"READ_QUERY"},{"privilegeType":"GRAPH","privilege":"CREATE_QUERY"},{"privilegeType":"QUERY","privilege":"UPDATE_QUERY"},{"privilegeType":"QUERY","privilege":"DROP_QUERY"},{"privilegeType":"QUERY","privilege":"INSTALL_QUERY"},{"privilegeType":"QUERY","privilege":"EXECUTE_QUERY"},{"privilegeType":"QUERY","privilege":"OWNER"},{"privilegeType":"GRAPH","privilege":"WRITE_DATASOURCE"},{"privilegeType":"GRAPH","privilege":"READ_ROLE"},{"privilegeType":"GRAPH","privilege":"WRITE_ROLE"},{"privilegeType":"GRAPH","privilege":"READ_USER"},{"privilegeType":"GLOBAL","privilege":"WRITE_USER"},{"privilegeType":"GRAPH","privilege":"READ_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"WRITE_PROXYGROUP"},{"privilegeType":"GLOBAL","privilege":"READ_FILE"},{"privilegeType":"GLOBAL","privilege":"WRITE_FILE"},{"privilegeType":"GLOBAL","privilege":"DROP_GRAPH"},{"privilegeType":"GLOBAL","privilege":"EXPORT_GRAPH"},{"privilegeType":"GLOBAL","privilege":"CLEAR_GRAPHSTORE"},{"privilegeType":"GLOBAL","privilege":"DROP_ALL"},{"privilegeType":"GRAPH","privilege":"ACCESS_TAG"},{"privilegeType":"GRAPH","privilege":"READ_DATA"},{"privilegeType":"GRAPH","privilege":"CREATE_DATA"},{"privilegeType":"GRAPH","privilege":"UPDATE_DATA"},{"privilegeType":"GRAPH","privilege":"DELETE_DATA"},{"privilegeType":"GRAPH","privilege":"APP_ACCESS_DATA"},{"privilegeType":"GRAPH","privilege":"READ_POLICY"},{"privilegeType":"GRAPH","privilege":"WRITE_POLICY"},{"privilegeType":"PACKAGE","privilege":"USE_FUNCTION"},{"privilegeType":"PACKAGE","privilege":"WRITE_FUNCTION"},{"privilegeType":"GLOBAL","privilege":"READ_WORKLOAD_QUEUE"},{"privilegeType":"GLOBAL","privilege":"WRITE_WORKLOAD_QUEUE"}]}
----
--
====

'''

=== grant privilege(s) to role(s)

`POST /gsql/v1/privileges/grant`

This endpoint is used to grant RABC privileges to specific roles

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST "http://localhost:14240/gsql/v1/privileges/grant?graph=recommend" -d "{"privileges":["READ_DATA", "CREATE_DATA", "UPDATE_DATA"], "vertexName": "user", "roles":["r1", "r2"]}"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"The privileges \"CREATE, READ, UPDATE\" are successfully granted on \"VERTEX user\" IN GRAPH recommend to role: r2\nThe privileges \"CREATE, READ, UPDATE\" are successfully granted on \"VERTEX user\" IN GRAPH recommend to role: r1\n","results":[{"privileges":{"1":{"privileges":[]},"recommend":{"privileges":[],"childPermissions":{"user":{"privileges":["READ_DATA","CREATE_DATA","UPDATE_DATA"]}}}},"role":"r1"},{"privileges":{"recommend":{"privileges":[],"childPermissions":{"user":{"privileges":["READ_DATA","CREATE_DATA","UPDATE_DATA"]}}}},"role":"r2"}]}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph the privilege(s) should be granted, 
or grant privilege(s) on global level if the parameter is missing
|===

'''

=== revoke privilege(s) from role(s)

`POST /gsql/v1/privileges/revoke`

This endpoint is used to revoke RABC privileges from specific roles

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST "http://localhost:14240/gsql/v1/privileges/revoke?graph=recommend" -d "{"privileges":["READ_DATA", "CREATE_DATA", "UPDATE_DATA"], "vertexName": "user", "roles":["r1", "r2"]}"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"The privileges \"CREATE, READ, UPDATE\" are successfully revoked on \"VERTEX user\" IN GRAPH recommend from role: r2\nThe privileges \"CREATE, READ, UPDATE\" are successfully revoked on \"VERTEX user\" IN GRAPH recommend from role: r1\n","results":[{"privileges":{"1":{"privileges":[]}},"role":"r1"},{"privileges":{},"role":"r2"}]}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph the privilege(s) should be revoked, 
or revoke privilege(s) on global level if the parameter is missing
|===

'''

=== show all roles

`GET /gsql/v1/roles`

Call this endpoint to show all roles, including built-in roles and user defined roles.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET "http://localhost:14240/gsql/v1/roles"
----
--
Response::
+
--
[source.wrap,console]
---- 	
{"error":false,"message":"","results":{"builtIn":{"global":["globalobserver","globaldesigner","superuser"],"local":["observer","queryreader","querywriter","designer","admin"]},"userDefinedRoles":{"1":["r1","r2","r3"],"recommend":["r4"]}}}
----
--
====

'''

=== Create roles

`POST /gsql/v1/roles`

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST "http://localhost:14240/gsql/v1/roles?graph=recommend" -d "{"roles":["r1", "r2"]}"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":"Successfully created local roles on graph 'recommend': [r1, r2]."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph to create local roles, 
or create global roles if the parameter is missing
|===

'''

=== Delete roles

`DELETE /gsql/v1/roles`

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X DELETE "http://localhost:14240/gsql/v1/roles?graph=recommend&role=r1,r2"
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":"Successfully dropped roles: [r1, r2]."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph to delete local roles, 
or delete global roles if the parameter is missing

| `roles`
| yes
| roles to delete
|===

'''

=== show one role

`GET /gsql/v1/roles/{roleName}`

Call this endpoint to show the info of a specific role.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET "http://localhost:14240/gsql/v1/roles/r1"
----
--
Response::
+
--
[source.wrap,console]
---- 	
{"error":false,"message":"","results":{"Graph":"recommend","roleName":"r1","isGlobal":false,"rolePrivileges":{"recommend":{"privileges":["READ_DATA","CREATE_DATA"]}}}}
----
--
====

'''

=== delete one role

`DELETE /gsql/v1/roles/{roleName}`

Call this endpoint to delete a specific role.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X DELETE "http://localhost:14240/gsql/v1/roles/r1"
----
--
Response::
+
--
[source.wrap,console]
---- 	
{"error":false,"message":"","results":"Successfully dropped roles: [r1]."}
----
--
====

'''

=== grant role(s) to user(s)

`POST /gsql/v1/roles/grant`

This endpoint is used to grant roles to specific users

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/roles/grant?graph=recommend' -d '{"roles":["observer", "r1"], "users":["user1", "user2"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":"Successfully granted roles [observer, r1] on graph 'recommend' to users [user1, user2]."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph the role(s) should be granted, 
or grant role(s) on global level if the parameter is missing
|===

'''

=== revoke privilege(s) from role(s)

`POST /gsql/v1/roles/revoke`

This endpoint is used to revoke roles from specific users

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/roles/revoke?graph=recommend' -d '{"roles":["observer", "r1"], "users":["user1", "user2"]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":"Successfully revoked roles [observer, r1] on graph 'recommend' from users [user1, user2]."}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| no
| in which graph the role(s) should be revoked, 
or revoke role(s) on global level if the parameter is missing
|===


'''

== Statistics

=== get cardinality statistics

`GET /gsql/v1/stats/cardinality`

This endpoint is used to fetch cardinality statistics.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET 'http://localhost:14240/gsql/v1/stats/cardinality?graph=recommend'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"vertex_counts":[{"count":5,"type":"user"}],"edge_counts":[{"count":5,"type":"edge3"},{"count":10,"from":"user","to":"product","type":"purchase"}]}}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| Get the cardinality stats of which graph
|===

'''

=== post cardinality statistics

`POST /gsql/v1/stats/cardinality`

This endpoint has to usage: 1) Fetch fresh up-to-date cardinality statistics and persist it to storage. 2) Persist user defined cardinality statistics to storage.

==== 1) Fetch fresh up-to-date cardinality statistics and persist it to storage

===== Example

[,tabs]
======
Request1::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/stats/cardinality?graph=ldbc_snb&vertex=Person'
----
--
Response1::
+
--
[source.wrap,console]
----
{"error": false,"message": "successfully persisted statistics"}
----
--
======

[,tabs]
======
Request2::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/stats/cardinality?graph=ldbc_snb&edge=LIKES&from=Person&to=Post'
----
--
Response2::
+
--
[source.wrap,console]
----
{"error": false,"message": "successfully persisted statistics"}
----
--
======

===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| Persist the cardinality stats to which graph

| `vertex`
| no
| Fetch fresh up-to-date cardinality stats for specific vertex types and persist them to storage

| `edge`
| no
| Fetch fresh up-to-date cardinality stats for specific edge types and persist them to storage, if `vertex` is not empty, this parameter will be ignored

| `from`
| no
| Fetch fresh up-to-date cardinality stats for not only specific edge types but also from specific vertex, if `edge` is not empty, this parameter will be ignored, this parameter usually used together with `to`.

| `to`
| no
| Fetch fresh up-to-date cardinality stats for not only specific edge types but also to specific vertex, if `edge` is not empty, this parameter will be ignored, this parameter usually used together with `from`.
|===

==== 2) Persist user defined cardinality statistics to storage.

===== Example

[,tabs]
======
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/stats/cardinality?graph=ldbc_snb' -d '{"vertex_counts":[{"type": "user","count": 5}], "edge_counts":[{"type":"edge3","count":5},{"type":"purchase","from":"user","to":"product","count":10}]}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"","results":{"vertex_counts":[{"count":5,"type":"user"}],"edge_counts":[{"count":5,"type":"edge3"},{"count":10,"from":"user","to":"product","type":"purchase"}]}}
----
--
======

===== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| Persist the cardinality stats to which graph
|===

'''

=== delete cardinality statistics

`DELETE /gsql/v1/stats/cardinality`

This endpoint is used to remove cardinality statistics from storage.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X DELETE 'http://localhost:14240/gsql/v1/stats/cardinality?graph=recommend'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"successfully deleted statistics"}
----
--
====

==== Parameters:

//[width="100%",cols="25%,25%,50%",options="header",]
[%autowidth]
|===
| Name | Required | Description

| `graph`
| yes
| Delete the cardinality stats of indicated graph from storage
|===

'''

=== get histogram statistics

`GET /gsql/v1/stats/cardinality`

This endpoint is used to fetch histogram statistics.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET 'http://localhost:14240/gsql/v1/stats/histogram' -d ' {"graph":"G", "edge":"E1", "from":"V1", "to":"V2", "attribute":"a", "bucket":10}'
----
--
Response::
+
--
[source.wrap,console]
----
[{"histogram": [{"rowsTotal": 104,"rowsUpper": 1,"upperBound": "2010-05-05 10:44:41"},{"rowsTotal": 12599,"rowsUpper": 1,"upperBound": "2012-06-09 21:24:20"},{"rowsTotal": 15986,"rowsUpper": 1,"upperBound": "2012-09-13 09:27:04"},{"rowsTotal": 1995,"rowsUpper": 1,"upperBound": "2010-11-14 17:07:00"},{"rowsTotal": 3570,"rowsUpper": 1,"upperBound": "2011-02-18 09:33:18"},{"rowsTotal": 4193,"rowsUpper": 1,"upperBound": "2011-05-24 21:54:24"},{"rowsTotal": 5481,"rowsUpper": 1,"upperBound": "2011-08-28 09:45:29"},{"rowsTotal": 752,"rowsUpper": 1,"upperBound": "2010-08-11 07:41:03"},{"rowsTotal": 8665,"rowsUpper": 1,"upperBound": "2012-03-06 08:31:44"},{"rowsTotal": 8880,"rowsUpper": 1,"upperBound": "2011-12-01 21:13:33"}]}]
----
--
====

'''

=== post histogram statistics

`POST /gsql/v1/stats/histogram`

This endpoint is used to persist new histogram statistics to storage.

==== Example

[,tabs]
=====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X POST 'http://localhost:14240/gsql/v1/stats/histogram' -d '{"graph":"G", "edge":"E1", "from":"V1", "to":"V2", "attribute":"a"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"0": {"rowsTotal": 151037,"rowsUpper": 90,"upperBound": 183},"1": {"rowsTotal": 0,"rowsUpper": 0,"upperBound": 399},"2": {"rowsTotal": 0,"rowsUpper": 0,"upperBound": 598},"3": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 710},"4": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 908},"5": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 1119},"6": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 1211},"7": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 1402},"8": {"rowsTotal": 0,"rowsUpper": 0,"upperBound": 1789},"9": {"rowsTotal": 1,"rowsUpper": 1,"upperBound": 1988}}
----
--
=====

'''

=== delete histogram statistics

`DELETE /gsql/v1/stats/histogram`

This endpoint is used to remove histogram statistics from storage.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X DELETE 'http://localhost:14240/gsql/v1/stats/histogram' -d ' {"graph":"G", "edge":"E1", "from":"V1", "to":"V2", "attribute":"a"}'
----
--
Response::
+
--
[source.wrap,console]
----
{"error": false,"message": "","results": "Deleting any histogram(s) for G.E1.a"}
----
--
====

'''

== System Utility

=== clear graph store

`GET /gsql/v1/clear-store`

This endpoint is used to clear graph store data but keep the schema.

==== Example

[,tabs]
====
Request::
+
--
[source,bash]
----
curl -H 'Content-Type: application/json' -X GET 'http://localhost:14240/gsql/v1/clear-store'
----
--
Response::
+
--
[source.wrap,console]
----
{"error":false,"message":"Successfully cleared graph store."}
----
--
====

'''
