= Edge Methods

This page lists all built-in edge methods that can be accessed by edge aliases using the dot (`.`) operator.

== `getAttr()`

[discrete]
===  Syntax

`e.getAttr( attrName, attrType )`

[discrete]
===  Description

Returns the value of an attribute of the edge.

[discrete]
===  Return type

The data type of the attribute itself.

[discrete]
===  Parameters

|===
| Parameter | Description | Data type

| `attrName`
| The name of the attribute.
| `STRING`

| `attrType`
| The type of the attribute
| `STRING`
|===

[discrete]
===  Example

If we have the following edge:

[source,text]
----
{
      "e_type": "User_Video",
      "directed": false,
      "from_id": "0",
      "from_type": "VidUser",
      "to_id": "2",
      "to_type": "Video",
      "attributes": {
        "rating": 5.2,
        "date_time": 0
}
----

Assume the alias of the edge is `e`:

[source,text]
----
e.getAttr("rating", "DOUBLE") -> 5.2
----

== `isDirected()`

[discrete]
===  Syntax

`e.isDirected()`

[discrete]
===  Description

Returns a boolean value indicating whether the edge is directed or undirected.

[discrete]
===  Return type

`BOOL`

[discrete]
===  Parameters

None.

== `setAttr()`

[discrete]
===  Syntax

`e.setAttr( attrName, attrNewValue )`

[discrete]
===  Description

Sets an attribute of an edge to a new value.

[discrete]
===  Return type

No return value.

[discrete]
===  Parameters

|===
| Parameter | Description | Data type

| `attrName`
| The name of the attribute. This argument must be a query parameter.
| `STRING`

| `attrNewValue`
| The new value of the attribute
| The type of the attribute. 
|===

[discrete]
===  Example

[source,gsql]
----
CREATE QUERY setAttrExample(STRING attr){ <1>
    Current = {v_type.*}
    S = SELECT s
            FROM Current:s -(e_type:e) - v_type:t
            WHERE t.attribute1 == "example_value"
            ACCUM e.setAttr(attr, TRUE); <2>
}
----
<1> The first argument of `e.setAttr` must be a query parameter.
Therefore, in this example we are passing a string value in the query parameter `attr`.
The string value should be the name of the attribute you want to call the function with.
<2> Selected edges will have their specified attribute set to `TRUE`.

