= Functions
:description: This section contains information on all functions in the GSQL query language.
:page-aliases: README.adoc, readme.adoc

This section contains information on all functions in the GSQL query language. Functions are categorized by data type when applicable, and by purpose when the function involves multiple data structures.

All built-in function names are case-insensitive. However, user-defined function names are case-sensitive

Built-in functions:

* xref:func/aggregation-functions.adoc[Aggregation functions]
* xref:func/datetime-functions.adoc[Datetime functions]
* xref:func/edge-methods.adoc[Edge methods]
* xref:func/jsonarray-methods.adoc[JSON array functions]
* xref:func/json-object-methods.adoc[JSON object functions]
* xref:func/mathematical-functions.adoc[Mathematical functions]
* xref:func/string-functions.adoc[String functions]
* xref:func/type-conversion-functions.adoc[Type conversion functions]
* xref:func/vertex-methods.adoc[Vertex functions]
* xref:func/miscellaneous-functions.adoc[Miscellaneous functions]

In GSQL, users can supplement the language by defining their own Query User-Defined Functions (Query UDF). To learn about how to define a Query UDF, see xref:func/query-user-defined-functions.adoc[Query User-Defined Functions].
