= Query User-Defined Functions
:pp: {plus}{plus}

In GSQL, users can supplement the language by defining their own query user-defined functions (query UDFs) in C{pp}. Query UDFs can be called in queries and subqueries to perform a set of defined actions and return a value like the built-in functions.

This page introduces the process to define a query UDF. Once defined, the new functions are added into GSQL automatically the next time GSQL is executed.

Creating, editing, or removing Query UDFs is done by downloading an `.hpp` file from the server, editing the file, and re-uploading via a GSQL command.

== Define a query UDF

Below are the steps to add a Query UDF to GSQL:

=== Step 1: Download current query UDF file

Use the `GET ExprFunctions` command in GSQL to download the current set of functions into a local file. The path can be absolute or relative to your current directory, but the file extension must be `.hpp`:

[source,gsql]
----
GSQL > GET ExprFunctions TO "/example/path/to/ExprFunctions.hpp"
GSQL > GET ExprFunctions TO "./ExprFunctions.hpp"

----

If your query UDF requires a user-defined struct or helper function, also use the `GET ExprUtil` command to download the current `ExprUtil` file:

[source,gsql]
----
GSQL > GET ExprUtil TO "/example/path/ExprUtil.hpp"
----

=== Step 2: Define C{pp} function

Define the C{pp} function inside the UDF file you just downloaded in Step 1. The definition of the function should include the keyword `inline`.

Below is a list of data types and where each is allowed in a function.

[header=true]
.Allowed Data Types
|===
|Data Type | Argument | Return | Function Body

| `bool` | Yes | Yes | Yes
| `int` | Yes | Yes | Yes
| `float` | Yes | Yes | Yes
| `double` | Yes | Yes | Yes
| `string` | Yes | Yes | Yes
| `std::string` | *No* | *No* | Yes
| xref:accumulators.adoc[Accumulators] | Yes | Yes | Yes

| All other C{pp} data types | *No* | *No* | Yes
|===

If the function requires a user-defined struct or helper function, define it in the `ExprUtil` file you downloaded in Step 1.

Below is an example of an `.hpp` file that contains two separate Query UDFs. The first function returns `true` if the passed value is greater than 3, and the second reverses a string.

.New code in ExprFunctions.hpp

[source,c++]
----
#include <algorithm>  // for std::reverse
inline bool greater_than_three (double x) {
  return x > 3;
}

inline string reverse(string str){
  std::reverse(str.begin(), str.end());
  return str;
}
----



[CAUTION]
====
If any code in `ExprFunctions.hpp` or `ExprUtil.hpp` causes a compilation error, GSQL will be unable to install _any_ new queries, whether containing user-defined functions or not.
====


=== Step 3: Upload files

After you have defined the function, use the `PUT` command to upload the files you modified.

[source,gsql]
----
GSQL > PUT ExprFunctions FROM "/path/to/udf_file.hpp"
PUT ExprFunctions successfully.
GSQL > PUT ExprUtil FROM "/path/to/utils_file.hpp"
PUT ExprUtil successfully.
----

The `PUT` command will automatically upload the files to all nodes in a cluster, overwriting any existing files that contain UDFs.

Once the files are uploaded, you will be able to call the Query UDF the next time GSQL is executed. This includes the next time you start the GSQL shell or execute GSQL scripts from a bash shell. If you are using GraphStudio, however, you will be able to use the queries without needing to refresh the page.

.Example of a GSQL query that uses the UDF

[source,gsql]
----
CREATE QUERY udfExample() FOR GRAPH minimalNet {
  DOUBLE x;
  BOOL y;

  x = 3.5;
  PRINT greater_than_three(x);
  y = greater_than_three(2.5);
  PRINT y;

  PRINT reverse("abc");
}
----



== Example

Suppose you are working in a distributed environment and want to add a function `rng()` that that returns a random double between 0 and 1.

Start by downloading the current UDF file with the `GET` command. In this example, we will place our download in the working directory and use the name `udf.hpp` in contrast to above, where it was named `ExprFunctions.hpp`.

[source,gsql]
----
GSQL > GET ExprFunctions TO "./udf.hpp"
----

In the downloaded file, add the function definition for the `rng()` function.

.udf.hpp

[source,c++]
----
inline double rng() {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution < double > distribution(0.0, 1.0);

    return distribution(gen);
    }

----

After adding your query, use the `PUT` command to upload the file. This will upload the file to all nodes in a cluster:

[source,gsql]
----
GSQL > PUT ExprFunctions FROM "./udf.hpp"
PUT ExprFunctions successfully.
----

The file has been uploaded and the UDF has now been added to GSQL. You can add it to a query, then run the commands `INSTALL QUERY` and `RUN QUERY` to test the `rng()` function. The following commands demonstrate the process with a one-line query called `rngExample` that simply prints the output of the new function `rng()`.

[source,gsql]
----
GSQL > CREATE QUERY rngExample() FOR GRAPH example_graph {PRINT rng();}
Successfully created queries: [rngExample].

GSQL > INSTALL QUERY rngExample
Start installing queries, about 1 minute ...
rngExample query: curl -X GET 'http://127.0.0.1:9000/query/example_graph/rngExample'. Add -H "Authorization: Bearer TOKEN" if authentication is enabled.
Select 'm1' as compile server, now connecting ...
Node 'm1' is prepared as compile server.

[=========================================================================================] 100% (1/1)
Query installation finished.

GSQL > RUN QUERY rngExample()
{
  "error": false,
  "message": "",
  "version": {
    "schema": 0,
    "edition": "enterprise",
    "api": "v2"
  },
  "results": [{"rng()": 0.51352}]
}
----
=== Using GitHub to Store UDFs

An alternative method is to connect GSQL with a GitHub repository for access to ExprFunctions and ExprUtil. This enables a simpler editing workflow rather than repeatedly using `PUT` to upload the file for every change.

In fact, GSQL will retrieve user source code files from GitHub before files uploaded via `PUT`, so long as the files exist.

The gadmin configuration parameters are as follows:

[source]
----
GSQL.GithubUserAcessToken # the credential, or "anonymous", empty means not using github
GSQL.GithubRepository     # e.g. tigergraph/ecosys
GSQL.GithubBranch         # optional, o/w use "master" branch, e.g. demo_github
GSQL.GithubPath           # path to the directory in the github that has TokenBank.cpp, ExprFunctions.hpp, ExprUtil.hpp, e.g. sample_code/src
GSQL.GithubUrl            # optional, used for github enterprise, e.g. https://api.github.com
----

Run the following `gadmin config set` commands to give GSQL access to GitHub.

[source]
----
gadmin config set GSQL.GithubUserAcessToken anonymous
gadmin config set GSQL.GithubRepository tigergraph/ecosys
gadmin config set GSQL.GithubBranch demo_github
gadmin config set GSQL.GithubPath sample_code/src
gadmin config apply
----

The file names must be `ExprFunctions.hpp` and `ExprUtil.hpp`. This is in contrast to the `PUT` method, where the files could have any file name.

[NOTE]
When the files are hosted on GitHub, the `typedef` statements and `include` directives must be part of the `.hpp` files. These statements are found at `AppRoot/dev/gdk/gsql/src/QueryUdf/ExprFunctions.hpp`.

For more information about the possibilities that GitHub file hosting brings, such as High Availability (HA), please see the corresponding xref:tigergraph-server:ha:ha-for-gsql-server.adoc[High Availability documentation.]