= Query User-Defined Functions
:pp: {plus}{plus}

In GSQL, users can supplement the language by defining their own query user-defined functions (query UDFs) in C{pp}. Query UDFs can be called in queries and subqueries to perform a set of defined actions and return a value like the built-in functions.

This page introduces the process to define a query UDF.
Once defined, the new functions are added into GSQL automatically the next time GSQL is executed.

== UDF files

UDFs are written in C{pp} in two files, `ExprFunctions.hpp` and `ExprUtil.hpp`:

* ExprFunctions is used for functions that are called directly in GSQL queries.
* ExprUtil contains structs or helper functions that are used by the functions in ExprFunctions.
The functions defined in `ExprUtil.hpp` cannot be used in a GSQL query.

This section first explains how to define a query UDF, then how to integrate query UDFs into GSQL.

[#_define_a_query_udf_in_cpp]
== Define a query UDF in C{pp}

User-defined functions are C{pp} functions with a certain set of allowed data types.
The function definition must include the keyword `inline`.

.Sample user-defined function
====
This is a sample function that returns `true` if the value passed to the function is greater than 3.
[source,c++]
----
inline bool greater_than_three (double x) {
  return x > 3;
}
----
====

[header=true]
.Allowed Data Types in User-Defined Functions
|===
|Data Type | Argument | Return | Function Body

| `bool` | Yes | Yes | Yes
| `int` | Yes | Yes | Yes
| `uint` | Yes | Yes | Yes
| `float` | Yes | Yes | Yes
| `double` | Yes | Yes | Yes
| `string` | Yes | Yes | Yes
| `std::string` | *No* | *No* | Yes
| xref:accumulators.adoc[Accumulators] | Yes | Yes | Yes

| All other C{pp} data types | *No* | *No* | Yes
|===

You can write your functions in the `ExprFunctions` file provided as a sample in TigerGraph Server installations, or create your own `.hpp` files from scratch.

If your function requires a user-defined struct or helper function, that struct or helper function must be defined in a separate `ExprUtil` file.

Below is an example of a short `ExprFunctions` file containing a single UDF that reverses a string. Note the `include` statement on the first line.

.New code in ExprFunctions.hpp

[source,c++]
----
#include <algorithm>  // for std::reverse
inline string reverse(string str){
  std::reverse(str.begin(), str.end());
  return str;
}
----

== Upload UDFs

There are two ways to modify these files to add user-defined functions to GSQL:

* Store UDF files in a GitHub repository, and configure GSQL to read from the repository.
** This is the recommended approach.
It also takes the highest precedence.
If GSQL is configured to read from GitHub for UDFs, and the configurations are valid, local UDF files are ignored.
* Use `gadmin` commands to upload a local UDF file to GSQL.
** Use this approach when your server does not have access to the internet and cannot access GitHub.

NOTE: There is a legacy method of xref:func/upload-udf-legacy.adoc[uploading] UDFs through GSQL.
For security reasons, the legacy method is not recommended.

=== Use GitHub to store UDFs

You can configure GSQL to read from a GitHub repository for ExprFunctions and ExprUtil.
This is TigerGraph's recommended approach to managing UDFs.

If GitHub access is configured, GSQL retrieves user source code files from GitHub before local files, so long as the files exist on GitHub.

[NOTE]
TigerGraph only allows one UDF file at a time.
Files on GitHub take priority. If GitHub is connected but files are missing, TigerGraph will look for a UDF file added locally.

New additions to the files in the GitHub repository are instantly available in GSQL.

You can retrieve ExprFunctions.hpp and ExprUtil.hpp from `AppRoot/dev/gdk/gsql/src/QueryUdf/ExprFunctions.hpp` and copy them to a Git repository of your choice.

[NOTE]
====
When the files are hosted on GitHub, the `typedef` statements and `include` directives must be part of the `.hpp` files.
These are included by default in the files located in the `/QueryUDF/` folder.
====

The file names must be `ExprFunctions.hpp` and `ExprUtil.hpp`. 
This is in contrast to the `PUT` method, where the files could have any file name.

The `gadmin` configuration parameters for setting up the connection to GitHub are as follows:

[header=true]
.Parameters for GitHub
|===
|Parameter | Description | Example

| `GSQL.GithubUserAcessToken` | The credential used to access the repository | `anonymous`
| `GSQL.GithubRepository` | The user and repository where the files are held | `sample_user/repository`
| `GSQL.GithubBranch`  | The branch to access | `main`
| `GSQL.GithubPath` | Path to the directory in the repository that has ExprFunctions.hpp and ExprUtil.hpp | `src/`
| `GSQL.GithubUrl` | Optional parameter used for GitHub Enterprise | `https://api.github.com`
|===

Use the xref:tigergraph-server:system-management:management-commands.adoc#_gadmin_config_set[`gadmin config set`] command to configure the aforementioned parameters to connect GSQL to the GitHub repository hosting your files.

The following is an example configuration.
Remember to run `gadmin config apply` after changing the parameters.
If GSQL is already running, run `gadmin restart all` to restart GSQL before the UDFs become available.

[source]
----
gadmin config set GSQL.GithubUserAcessToken anonymous
gadmin config set GSQL.GithubRepository tigergraph/ecosys
gadmin config set GSQL.GithubBranch demo_github
gadmin config set GSQL.GithubPath sample_code/src
gadmin config apply
----

After the parameters are successfully configured, you can access your UDFs in new queries right away.

=== Upload a local UDF file through `gadmin`

You can configure `gadmin` to upload a local file to the GSQL server.
Once uploaded, the UDF file is available to all nodes in a TigerGraph cluster.
Moving the local file after uploading does not affect the UDF available to GSQL.

==== Modify current query UDF file

Run the following command to retrieve the current UDF file to a specified location on the server.
Replace `<path_to_file>` with the filepath where you want the UDF file:

[.wrap,console]
----
$ gadmin config get GSQL.UDF.ExprFunctions  >  <path_to_file> <1>
$ gadmin config get GSQL.UDF.ExprUtil > <path_to_file> <2>
----
<1> This retrieves `ExprFunctions` where the UDFs are defined.
<2> This retrieves `ExprUtil`, where helper functions are defined.

For example:

[.wrap,console]
----
$ gadmin config get GSQL.UDF.ExprFunctions  >  /home/tmpExprFunctions.hpp
----

==== Define your function

Write your function in ExprFunctions and any helper functions in ExprUtil.

[CAUTION]
====
If any code in `ExprFunctions.hpp` or `ExprUtil.hpp` causes a compilation error, GSQL will be unable to install _any_ new queries, whether containing user-defined functions or not.
====

==== Upload query UDF file

After modifying the file, run the following command to upload the modified file.
Replace `<path_to_file>` with the path of the UDF file:

[.wrap,console]
----
$ gadmin config set GSQL.UDF.ExprFunctions   @<path_to_file>
$ gadmin config apply
$ gadmin restart gsql
----


For example:

[.wrap,console]
----
$ gadmin config set GSQL.UDF.ExprFunctions   @/home/tmpExprFunctions.hpp
$ gadmin config apply
$ gadmin restart gsql
----


WARNING: If you set `GSQL.UDF.EnablePutExpr` to `false` after uploading UDFs using the `PUT` command, GSQL ignores the functions uploaded through the `PUT` command and reads those functions from `GSQL.UDF.ExprUtil` and `GSQL.UDF.ExprFunctions` instead.

== Example

Suppose you are working in a distributed environment and want to add a function `rng()` that that returns a random double between 0 and 1.
In this example, suppose you want to modify the ExprFunctions file locally rather than using GitHub.

Start by downloading the current UDF file with.
In this example, we place our download in the working directory and use the name `udf.hpp` in contrast to above, where it was named `ExprFunctions.hpp`, to illustrate the flexibility of the naming scheme.

[source,console]
----
$ gadmin config get GSQL.UDF.ExprFunctions  >  ./udf.hpp
----

In the downloaded file, add the function definition for the `rng()` function in C++.

.udf.hpp
[source.wrap,c++]
----
inline double rng() {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution < double > distribution(0.0, 1.0);

    return distribution(gen);
}
----

After adding your function, upload the file with `gadmin`:

[source.wrap,console]
----
$ gadmin config set GSQL.UDF.ExprFunctions   @/home/tmpExprFunctions.hpp
$ gadmin config apply
$ gadmin restart gsql
----

The file has been uploaded and the UDF has now been added to GSQL.
You can now use this function in a GSQL query.


