= Type Conversion Functions

The functions on this page are used to convert data from one type to another in the GSQL query language.

== `parse_json_array()`

=== Syntax

`parse_json_array( str )`

=== Description

Converts a string into a JSON array. The string must be properly formatted, or the function will generate a run-time error. To be properly formatted, besides having the proper nesting and matching of curly braces `{ }` and brackets `[ ]`, each value field must be one of the following:

* a string
* a number
* a boolean
* a JSONOBJECT - Each key of a key-value pair must be a string in double quotes.
* a JSON array

=== Return type

`JSONARRAY`

=== Parameters

|===
| Parameter | Description | Data type

| `str`
| The string to be converted into a JSON array.
| `STRING`
|===

=== Example

[source,javascript]
----
parse_json_array("[123]") -> [123]
----

== `parse_json_object()`

=== Syntax

`parse_json_object( str )`

=== Description

Converts a string into a JSON object. The string must be properly formatted, or the function will generate a run-time error. To be properly formatted, besides having the proper nesting and matching of curly braces `{ }` and brackets `[ ]`, each value field must be one of the following:

* a string
* a number
* a boolean
* a JSONOBJECT - Each key of a key-value pair must be a string in double quotes, and the quotes need to be escaped with a backlash-escape `\`. However, if you are supplying the string in GraphStudio as a parameter, you do not need the backlash-escape since string values are not enclosed in double quotes.
* a JSON array

=== Return type

`JSONOBJECT`

=== Parameters

|===
| Parameter | Description | Data type

| `str`
| The string to be converted into a JSON object.
| `STRING`
|===

=== Example

[source,javascript]
----
parse_json_object("{\"abc\":123}")  -> {"abc": 123}
----

== `str_to_int ()`

=== Syntax

`str_to_int (str)`

=== Description

Converts a string to an integer.

=== Return type

`INT`

=== Parameters

|===
| Parameter | Description | Data type

| `str`
| The string that contains an integer to convert to an integer
| `STRING`
|===

== `to_datetime ()`

=== Syntax

`to_datetime ( str )`

=== Description

Converts a string value into a `DATETIME` value.

=== Return type

`DATETIME`

=== Parameters

|===
| Parameter | Description | Data type

| `str`
| A string value
| `STRING`
|===

=== Example

[source,javascript]
----
to_datetime("2020-01-02 01:02:03") -> 2020-01-02 01:02:03
----

== `to_string()`

=== Syntax

`to_string(num)`

=== Description

Converts a number to a string.

=== Return type

`STRING`

=== Parameters

|===
| Parameter | Description | Data type

| `num`
| The number to turn into a string
| Number
|===
