= Uploading User-Defined Functions (Legacy)
:sectnums:


TigerGraph offers the ability to upload UDFs directly from GSQL.
This allows authorized users to upload UDF files without having to access the server file system.

For security reasons, this option is disabled by default and must be turned on by the TigerGraph Linux user.
Once enabled, UDFs are no longer managed by `gadmin`.
If your host machine is not completely secure, it is strongly recommended that you xref:func/query-user-defined-functions.adoc[upload UDFs through `gadmin`] instead, which ensures that UDFs can only be modified by users with sufficient access to the underlying file system of the server.


== Enable uploading UDFs through GSQL

Run the following command to enable uploading query UDFs to GSQL:

[source.wrap,console]
----
$ gadmin config set GSQL.UDF.EnablePutExpr true
$ gadmin config apply
$ gadmin restart gsql
----


== Modify current query UDF file

Use the `GET ExprFunctions` command in GSQL to copy the current set of functions into a local file.
The path can be absolute or relative to your current directory, but the file extension must be `.hpp`:

[source,gsql]
----
GSQL > GET ExprFunctions TO "/example/path/to/ExprFunctions.hpp"
GSQL > GET ExprFunctions TO "./ExprFunctions.hpp"

----

If your query UDF requires a user-defined struct or helper function, also use the `GET ExprUtil` command to download the current `ExprUtil` file:

[source,gsql]
----
GSQL > GET ExprUtil TO "/example/path/ExprUtil.hpp"
----

== Define your function

Write your function in ExprFunctions and any helper functions in ExprUtil as described in xref:func/query-user-defined-functions.adoc#_define_a_query_udf_in_cpp[Query User-Defined Functions].

[CAUTION]
====
If any code in `ExprFunctions.hpp` or `ExprUtil.hpp` causes a compilation error, GSQL will be unable to install _any_ new queries, whether containing user-defined functions or not.
====

== Upload the updated query UDF file

After you have defined the function, use the `PUT` command to store the files you modified.

[source,gsql]
----
GSQL > PUT ExprFunctions FROM "/path/to/udf_file.hpp"
PUT ExprFunctions successfully.
GSQL > PUT ExprUtil FROM "/path/to/utils_file.hpp"
PUT ExprUtil successfully.
----

The `PUT` command will automatically store the files in all nodes in a cluster, overwriting any existing files that contain UDFs.

Once the files are stored, you will be able to call the Query UDF the next time GSQL is executed.
This includes the next time you start the GSQL shell or execute GSQL scripts from a bash shell.
If you are using GraphStudio, however, you will be able to use the queries without needing to refresh the page.

.Example of a GSQL query that uses the UDF
[source,gsql]
----
CREATE QUERY udf_example() FOR GRAPH Minimal_Net {
  DOUBLE x;
  BOOL y;

  x = 3.5;
  PRINT greater_than_three(x);
  y = greater_than_three(2.5);
  PRINT y;
}
----