= DDL Keywords & Reserved Words

== GSQL Reserved Words

The following words are reserved for use by the Data Definition Language. That is, a graph schema or loading job may not use any of these words for the *name of a vertex type, edge type, graph name, tag, or attribute*. +
There is a separate list for xref:../../querying/appendix-query/query-language-reserved-words.adoc[Reserved Words in the *Query Language*]. +
The compiler will reject the use of a reserved word as well as any word beginning with a reserved prefix as a user-defined identifier.

=== History

* v3.1: Added reserved prefix `gsql_sys_`

=== Reserved prefixes:

* `gsql_sys_`

=== Reserved word list:

[source,text]
----
ACCUM               ADD                 ADMIN               ALL
ALLOCATE            ALTER               AND                 ANY
AS                  ASC                 AVG                 BAG
BATCH               BETWEEN             BIGINT              BLOB
BOOL                BOOLEAN             BOTH                BREAK
BY                  CALL                CASCADE             CASE
CATCH               CHAR                CHARACTER           CHECK
CLOB                COALESCE            COMPRESS            CONST
CONSTRAINT          CONTINUE            COUNT               CREATE
CURRENT_DATE        CURRENT_TIME        CURRENT_TIMESTAMP   CURSOR
DATA_SOURCE         DATETIME            DATETIME_ADD        DATETIME_SUB
DECIMAL             DECLARE             DEFAULT             DELETE
DESC                DISTRIBUTED         DO                  DOUBLE
DROP                EDGE                ELSE                ELSEIF
END                 ESCAPE              EXCEPTION           EXISTS
EXPRFUNCTIONS       EXPRUTIL            FALSE               FILE
FILENAME            FILTER              FIXED_BINARY        FLATTEN_JSON_ARRAY
FLOAT               FOR                 FOREACH             FROM
GLOBAL              GRAPH               GROUP               GROUPBYACCUM
HAVING              HEADER              HEAPACCUM           IF
IGNORE              IN                  INDEX               INPUT_LINE_FILTER
INSERT              INT                 INT16               INT32
INT32_T             INT64_T             INT8                INTEGER
INTERPRET           INTERSECT           INTO                IS
ISEMPTY             JOB                 JOIN                JSONARRAY
JSONOBJECT          KAFKA               KEY                 LEADING
LIKE                LIMIT               LIST                LOAD
LOADACCUM           LOG                 LONG                MAP
NOT                 NOW                 NULL                OFFSET
ON                  OR                  ORDER               PINNED
POST_ACCUM          PRIMARY             PRIMARY_ID          PRINT
PROXY               QUERY               QUIT                RAISE
RANGE               REDUCE              REPLACE             RETURN
RETURNS             S3                  SAMPLE              SELECT
SELECTVERTEX        SET                 STATIC              STRING
SUM                 TARGET              TEMP_TABLE          THEN
TO                  TOKEN               TOKENBANK           TOKEN_LEN
TO_CSV              TO_DATETIME         TO_FLOAT            TO_INT
TRAILING            TRIM                TRUE                TRY
TUPLE               TYPEDEF             UINT                UINT16
UINT32              UINT32_T            UINT64_T            UINT8
UINT8_T             UNION               UPDATE              UPSERT
USING               VALUES              VERTEX              WHEN
WHERE               WHILE
----

== GSQL Non-Reserved Keywords

These keywords in the language are non-reserved, so users make use them for user-defined identifiers.

=== History

* v3.1: Added `DESCRIPTION,` `TAG`, `TAGS`

=== Non-reserved keyword list:

[source,text]
----
ABORT               API                 APPROX_COUNT        ATTRIBUTE
BEGIN               CHANGE              CLEAR               CONCAT
DATA                DATASRC             DECRYPT             DEFAULT
DEFINE              DESCRIPTION         DIRECTED            EMPTY
EXIT                EXPORT              EXPR_FUNC           EXPR_UTIL
EXTERN              FILENAMEVAR         FLATTEN             FLATTENJSON
GENERATEDATA        GET                 GRANT               HELP
ICON                IMPORT              INSTALL             JSON
LOADING             LOCAL               LS                  MAX
MIN                 MINUS               NUMERIC             OPTION
OVERWRITE           PAIR                PASSWORD            PUT
RECOMPILE           REJECT_LINE_RULE    RESUME              REVOKE
ROLE                RUN                 SCHEMA_CHANGE       SCHEMA
SECONDARY_ID        SECRET              SEPARATOR           SHOW
SPLIT               STATS               STATUS              STORE
SUBSTR              SYNTAX              TAG                 TAGS
TEMPLATE            TK                  TOFLOAT             TOINT
TOKEN_BANK          TOKENLEN            UNDIRECTED          USE
USER                USERS               VAL                 VECTOR
VERSION             VOID                WITH
----
