= Statistics REST APIs (Preview Feature)

The endpoints on this page calculate cardinality and histogram statistics of vertex and edge types and attributes.
The statistics are required for effective optimization.

[IMPORTANT]
====
Query Optimizer is currently a Preview Feature. Preview Features give users an early look at future production-level features.

Preview Features should not be used for production deployments.
====

== Cardinality

The following endpoints compute, fetch and delete vertex and edge counts (cardinality) of a graph.


include::partial$cardinality-api.adoc[]

== Histogram

Histograms store information about the distribution of attribute values. They are computed using an Equi-Width computation method. This means, given a target bucket count, a histogram will be computed with up to that many buckets (see bucket parameter for more details). 

**Buckets**: Increasing the number of buckets will increase the granularity of the computed histogram, while decreasing the number of buckets will increase compaction. Choosing the right bucket count should be done based on the use case first, then adjusted afterwards if necessary. Please see recommendations below for best practices.

NDV (Number of Distinct Values): this value is approximated for each bucket. For discrete datatypes (uint, int, datetime) this will represent the maximum potential NDV. For floating point, non discrete datatypes (float, double), assuming uniform distribution means assuming all values in a bucket are distinct. Primary id’s always have exact NDV values, since they are by definition all unique values.

Empty buckets in the histogram are denoted by a totalCount, upperCount, and ndv of zero. upperBound will have the max value for that bucket. This is only a theoretical limit for the bucket, and the totalCount should be relied on to determine whether a bucket is empty

Supported Data Types are: UINT, INT, DATETIME, FLOAT, DOUBLE

include::partial$histogram-api.adoc[]

