= Enabling Cost-Based Optimization
:sectnums:
:description: Steps to enable the query optimizer.

This page walks you through the steps to enable cost-based optimization.

== Before you begin
* You have created a query that contains a xref:select-statement/index.adoc[`SELECT` statement] that uses a xref:select-statement/index.adoc#_path_pattern[path pattern] in its `FROM` clause with one or more hops.
* You have the privilege to install queries on the graph where you are operating.

== Procedure
The following is the procedure to enable cost-based optimization when installing a query.

=== Identify referenced types and attributes
You need to identify the vertex and edge attributes for which you need to compute histogram statistics, which refers to the distribution of values for an attribute.

You need to compute histograms for the following attributes:

* Any vertex attribute referenced in a xref:select-statement/index.adoc#_where[`WHERE` clause] in a `SELECT` statement in the query.
* Any _refined edge type_ attribute referenced in a xref:select-statement/index.adoc#_where[`WHERE` clause] in a `SELECT` statement in the query.
** A _refined edge type_ means an edge type with a specified pair of `from` and `to` vertex types as well as their reverse edge types if they exist.

If you are not sure which types and attributes you need to compute histogram data for a query, you can try <<_install_query_with_cost_option,installing that query with the cost-based optimizer enabled>> first.
The optimizer produces a helpful recommendation if it sees any types/attributes that don't have statistics computed for them.

For example, to optimize the following query:

[.wrap,gsql]
----
CREATE OR REPLACE QUERY example3() FOR GRAPH ldbc_snb SYNTAX V2 {

 vSet = SELECT p
        FROM Tag:t - (<HAS_TAG) - Comment:m - (<LIKES:e) - Person:p
        WHERE p.gender == "female" AND t.id != 100 AND e.creationDate >  to_datetime("2010-10-01 16:00")
        LIMIT 50;
        PRINT vSet;
}
----

You need the following histogram statistics:

** `gender` attribute of type `Person`
** `id` attribute of type `Tag`
** `creationDate` attribute of type `LIKES` from `Person` to `Comment`.

=== Compute histogram data
To compute histogram data, use the xref:query-optimizer/stats-api.adoc#_compute_histogram_statistics[`POST :14240/gsqlserver/gsql/stats/histogram` endpoint].

For example, to compute the histogram data for attribute `gender` of vertex type `Person` on graph `ldbc_snb`, make the following request:

[.wrap,console]
----
$ $ curl --user tigergraph:tigergraph -X POST \
"http://localhost:14240/gsqlserver/gsql/stats/histogram" \
-d '{"graph":"ldbc_snb", "vertex":"Person", "attribute":"gender", "buckets":10}'
----

To compute the histogram data for attribute `creationDate` of refined edge type `LIKES` from vertex type `Person` to vertex type `Comment`, make the following request:

[.wrap,console]
----
$ curl -s --user tigergraph:tigergraph -X POST \
"http://localhost:14240/gsqlserver/gsql/stats/histogram" \
-d '{"graph":"ldbc_snb", "edge":"LIKES", "from":"Person", "to":"Comment", "attribute":"creationDate", "buckets":10}' | jq .
----

For best results, compute the histogram data for every attribute referenced in a `WHERE` clause of a `SELECT` statement.

[#_install_query_with_cost_option]
=== Install query with `-cost` option

Now that the relevant statistics are available to the query optimizer, you can install the query with cost-based optimization.
To use the cost-based optimization during installation, use the xref:query-operations.adoc#_install_query[`-cost` option] when installing the query.

For example, to install the query `example3`, run `INSTALL QUERY example3 -cost`.

Alternatively, set xref:basics:system-and-language-basics.adoc#_session_parameters[the `cost_opt` session parameter] to true by running `set cost_opt = true` in the GSQL shell.
This enables cost-based optimization for the rest of your GSQL session.
You no long need to supply the `-cost` option when installing queries if the `cost_opt` parameter is set to true.

If you missed any cardinality or histogram data, the optimizer warns you about which types are missing, so you can compute the data for any missing type or attribute.
