= Statistics REST APIs (Preview Feature)

The endpoints on this page calculate cardinality and histogram statistics of vertex and edge types and attributes.
The statistics are required for effective optimization.

[IMPORTANT]
====
Query Optimizer is currently a Preview Feature. Preview Features give users an early look at future production-level features.

Preview Features should not be used for production deployments.
====

== Cardinality

The following endpoints compute, fetch and delete vertex and edge counts (cardinality) of a graph.


include::partial$cardinality-api.adoc[]

== Histogram

Histograms store information about the distribution of attribute values. They are computed using an Equi-Width computation method. This means, given a target bucket count, a histogram will be computed with up to that many buckets (see bucket parameter for more details). 

**Bucket Count**: Increasing the number of buckets will increase the granularity of the computed histogram, while decreasing the number of buckets will increase compaction. Choosing the right bucket count should be done based on the use case first, then adjusted afterwards if necessary. Please see recommendations below for best practices.

**NDV** (Number of Distinct Values): This value is approximated for each bucket. 

* Integral datatypes (UINT, INT, DATETIME): the NDV value represents an upper bound (the actual NDV may be lower).
* Floating point numeric values (FLOAT, DOUBLE): the NDV is approximated by assuming all values are distinct. 
* Primary id’s: the NDV represents the actual NDV and no approximation is used.

**Supported Data Types**: UINT, INT, DATETIME, FLOAT, DOUBLE

include::partial$histogram-api.adoc[]
