= Example - A Recommender

We have demonstrated the basic pattern match syntax. You should fully understand the basics by this point. In this section, we show two end-to-end solutions using the pattern match syntax.

== A Recommendation Application

In this example, we want to recommend some messages (comments or posts) to the person Viktor Akhiezer.

How do we do this?

One way is to find others who like the same messages Viktor likes, then recommend the messages that Others like but Viktor has not seen. The pattern can be sketched out as follows:

* Viktor - (Likes>) - Message - (<Likes) - Others
* Others - (Likes>) - NewMessage
* Recommend NewMessage to Viktor

However, this is too granular. We are overfitting the message-level data with a collaborative filtering algorithm.

Intuitively, two persons are similar to each other when their "liked" messages fall into the same category - here represented by the set of tags attached to each message.

As a result, one way to avoid overfitting is to go one level upward. Instead of looking at common messages, we look at their tags. We consider Person A and Person B  similar if they like messages that belong to the same tag. This scheme fixes the overfitting problem. In pattern match vocabulary, we have

* Viktor - (Likes>) - Message -  (Has>) - *Tag* -  (<Has) -  Message - (<Likes) - Others
* Others - (Likes>) -  NewMessage
* Recommend NewMessage to Viktor

== GSQL recommend_message Application

This time, we create the query first and interpret the query by calling the query name with parameters. +
If we are satisfied with this query, we can use `INSTALL QUERY queryName` to install the query, increasing performance.

.GSQL Recommendation Algorithm 

[source,gsql]
----
include::appendix:example$ldbc_snb/example_recommendation_algorithm.gsql[]

INTERPRET QUERY recommend_message ("Viktor", "Akhiezer")
// try the second person with just parameter change.
INTERPRET QUERY recommend_message ("Adriaan", "Jong")
----


.Output of App1

[source,coffeescript]
----
include::appendix:example$ldbc_snb/example_recommendation_algorithm_results.json[]

----

=== Install the query

When you are satisfied with your query in the GSQL interpreted mode, you can install it as a generic service. This speeds up querying considerably.
Since we have been using `CREATE QUERY ...` syntax, the query is added into the catalog, and we can set the syntax version and install it.

.Prepare to Install Query

[source,gsql]
----
// before installing the query, need to set the syntax version
SET syntax_version="v2"
USE GRAPH ldbc_snb

// install query
INSTALL QUERY recommend_message
----



.Run the Installed Query

[source,gsql]
----
GSQL > INSTALL QUERY recommend_message
Start installing queries, about 1 minute ...
recommend_message query: curl -X GET 'http://127.0.0.1:9000/query/ldbc_snb/recommend_message?fn=VALUE&ln=VALUE'. Add -H "Authorization: Bearer TOKEN" if authentication is enabled.

[========================================================================================================] 100% (1/1)
GSQL > run query recommend_message("Viktor", "Akhiezer")
{
  "error": false,
  "message": "",
  "version": {
    "schema": 0,
    "edition": "enterprise",
    "api": "v2"
  },
  "results": [{"recommended_message": [
    {
      "v_id": "549760294602",
      "attributes": {
        "recommended_message.@rank": 4855.49219,
        "recommended_message.content": "About Indira Gandhi, Gandhi established closer relatAbout Mick Jagger, eer of the band. In 1989, he waAbout Ho Chi Minh, ce Unit and ECA International, About Ottoman Empire,  After t"
      },
      "v_type": "Post"
    },
    {
      "v_id": "549760292109",
      "attributes": {
        "recommended_message.@rank": 4828.7251,
        "recommended_message.content": "About Ho Chi Minh, nam, as an anti-communist state, fought against the communisAbout Shiny Happy People, sale in the U."
      },
      "v_type": "Post"
    }
  ]}]
}
----

The previous example uses log-cosine as a similarity measurement. We can also use cosine similarity by using two persons' liked messages.

.GSQL Recommendation Algorithm 2

[source,gsql]
----
include::appendix:example$ldbc_snb/example_recommendation_algorithm_2.gsql[]

INTERPRET QUERY recommend_message ("Viktor", "Akhiezer")
// try the second person with just parameter change.
INTERPRET QUERY recommend_message ("Adriaan", "Jong")
----


