= 準備

== はじめに

このチュートリアルでは、パターンマッチングのクエリの作成と実行方法について説明します。パターンマッチングはTigerGraph 2.4以降のバージョンで提供されています。

xref:tutorials:gsql-101/README.adoc[GSQL 101]のチュートリアルを終了していることを前提としています。そうでない場合は、先にGSQL 101を完了してからこちらを始めてください。

[NOTE]
====
このチュートリアルはTigerGraph 3.0のリリース時に更新されています。古いバージョンをお使いの場合は、そのバージョンのドキュメントに変更してください。
====

=== グラフパターンとは

グラフパターンは、グラフスキーマに表示されるトラバーサルトレースです。パターンは繰り返されるステップを含むことができます。パターンには線状のトレースもあれば、線以外（ツリー、円など）のトレースもあります。例えば、Person という頂点タイプとFriendshipというエッジタイプによって構成される単純なスキーマの場合、パターンは次のようにその単純なスキーマ内のトレースを指す場合もあれば、

[source,text]
----
Person - (Friendship) - Person - (Friendship) - Person
----

次のように *2を使って、2つの連続したFriendshipのエッジを指す場合もあります。

[source,text]
----
Person - (Friendship*2) - Person
----

=== パターンマッチングとは

パターンマッチングは、指定されているクエリパターンが適合するサブグラフをデータグラフ内で探索する処理です。

== TigerGraph環境の準備

ここでは、TigerGraphインスタンスのすべての権限を持つ唯一のユーザーとして実行していることを前提としています。マルチユーザーのエンタープライズエディションをお使いの場合は、データベース管理者の方と相談してください。空のグラフに対する、デザイナーまたは管理者の権限が必要です。チュートリアルの各所に、ファイルをダウンロードするリンクがあります。大半のファイルは小さいものですが、グラフデータファイルは解凍すると1GBになります。

まず、GSQLにアクセスできること、お使いのバージョンが3.0以上であることを確認してください。

. Linuxシェルを開きます。
. 次のように `gsql` と入力します。GSQLシェルのプロンプトが次のように表示されます。
. GSQLシェルにversionと入力します。次のように、2.4以上と表示されるでしょう。そうでない場合には、最新のバージョンを https://www.tigergraph.co.jp/get-tigergraph/ からダウンロードしインストールしてください。
+
.Linuxシェル
+
[source,bash]
----
$ gsql
GSQL > version
GSQL version: 3.0
----
+


. GSQLシェルが起動しない場合は、「gadmin start all」でシステムをリセットしてみてください。これにより、まだ開始していない各サービスが起動されます。それでもうまく行かない場合には、「  xref:3.4@tigergraph-server:gadmin:management-with-gadmin.adoc[TigerGraphをgadminで管理]」のドキュメントをご覧ください。
. データカタログが空の状態で、シェルを起動させる必要があります。必要であれば、まず `drop all` を実行して、カタログをクリアしてください。

=== チートシート

以下は  xref:tutorials:gsql-101/README.adoc[GSQL 101]で説明があった一般的なコマンドです。

* Linuxシェルのコマンドには *`%`* の接頭文字がついています。大多数のgadminコマンドは、TigerGraphの管理者権限がなければ実行できません。
* GSQLシェルのコマンドには *`GSQL>`* の接頭文字がついています。

[width="100%",cols="<50%,<50%",options="header",]
|===
|コマンド |説明
|% gsql |GSQLシェルにインタラクティブモードで入る
|% gsql '<GSQLコマンドの文字列>' |GSQLコマンドを1つ実行する
|% gadmin status |TigerGraphサービスのステータスを確認する +
+
(グラフストアが空の場合は、 +
+
一部のステータスが赤くフラグされることがあります)
|% gadmin restart |TigerGraphサービスを再起動する
|GSQL> ls |グラフスキーマ、読み込みジョブ、クエリをリストする
|GSQL> show user |ユーザー名とロールを表示する
|GSQL> drop all a|
スキーマ全体、すべてのデータ、すべてのジョブ、

すべてのクエリを削除する

|GSQL> exit |GSQLのインタラクティブシェルを終了する
|===
